#reset
# TimeSlot.delete_all

TimeSlot.create([
{ time: Time.zone.parse('12:00'), weekday: true, court_id: 1, covid_slot: true},
{ time: Time.zone.parse('12:40'), weekday: true, court_id: 1, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('13:00'), weekday: true, court_id: 1, covid_slot: true},
{ time: Time.zone.parse('13:40'), weekday: true, court_id: 1, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('14:00'), weekday: true, court_id: 1, covid_slot: true},
{ time: Time.zone.parse('14:40'), weekday: true, court_id: 1, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('15:00'), weekday: true, court_id: 1, covid_slot: true},
{ time: Time.zone.parse('15:40'), weekday: true, court_id: 1, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('16:00'), weekday: true, court_id: 1, covid_slot: true},
{ time: Time.zone.parse('16:40'), weekday: true, court_id: 1, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('17:00'), weekday: true, court_id: 1, covid_slot: true},
{ time: Time.zone.parse('17:40'), weekday: true, court_id: 1, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('18:00'), weekday: true, court_id: 1, covid_slot: true},
{ time: Time.zone.parse('18:40'), weekday: true, court_id: 1, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('19:00'), weekday: true, court_id: 1, covid_slot: true},
{ time: Time.zone.parse('19:40'), weekday: true, court_id: 1, covid_slot: true, cleaning: true, bank_holiday: false},
{ time: Time.zone.parse('20:00'), weekday: true, court_id: 1, covid_slot: true, bank_holiday: false},
{ time: Time.zone.parse('20:40'), weekday: true, court_id: 1, covid_slot: true, cleaning: true, bank_holiday: false},
{ time: Time.zone.parse('21:00'), weekday: true, court_id: 1, covid_slot: true, bank_holiday: false},
{ time: Time.zone.parse('21:40'), weekday: true, court_id: 1, covid_slot: true, cleaning: true, bank_holiday: false},
{ time: Time.zone.parse('22:00'), weekday: true, court_id: 1, covid_slot: true, bank_holiday: false},
{ time: Time.zone.parse('22:40'), weekday: true, court_id: 1, covid_slot: true, cleaning: true, bank_holiday: false},

{ time: Time.zone.parse('12:10'), weekday: true, court_id: 2, covid_slot: true},
{ time: Time.zone.parse('12:50'), weekday: true, court_id: 2, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('13:10'), weekday: true, court_id: 2, covid_slot: true},
{ time: Time.zone.parse('13:50'), weekday: true, court_id: 2, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('14:10'), weekday: true, court_id: 2, covid_slot: true},
{ time: Time.zone.parse('14:50'), weekday: true, court_id: 2, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('15:10'), weekday: true, court_id: 2, covid_slot: true},
{ time: Time.zone.parse('15:50'), weekday: true, court_id: 2, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('16:10'), weekday: true, court_id: 2, covid_slot: true},
{ time: Time.zone.parse('16:50'), weekday: true, court_id: 2, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('17:10'), weekday: true, court_id: 2, covid_slot: true},
{ time: Time.zone.parse('17:50'), weekday: true, court_id: 2, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('18:10'), weekday: true, court_id: 2, covid_slot: true},
{ time: Time.zone.parse('18:50'), weekday: true, court_id: 2, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('19:10'), weekday: true, court_id: 2, covid_slot: true},
{ time: Time.zone.parse('19:50'), weekday: true, court_id: 2, covid_slot: true, cleaning: true, bank_holiday: false},
{ time: Time.zone.parse('20:10'), weekday: true, court_id: 2, covid_slot: true, bank_holiday: false},
{ time: Time.zone.parse('20:50'), weekday: true, court_id: 2, covid_slot: true, cleaning: true, bank_holiday: false},
{ time: Time.zone.parse('21:10'), weekday: true, court_id: 2, covid_slot: true, bank_holiday: false},
{ time: Time.zone.parse('21:50'), weekday: true, court_id: 2, covid_slot: true, cleaning: true, bank_holiday: false},
{ time: Time.zone.parse('22:10'), weekday: true, court_id: 2, covid_slot: true, bank_holiday: false},
{ time: Time.zone.parse('22:50'), weekday: true, court_id: 2, covid_slot: true, cleaning: true, bank_holiday: false},

{ time: Time.zone.parse('12:20'), weekday: true, court_id: 3, covid_slot: true},
{ time: Time.zone.parse('13:00'), weekday: true, court_id: 3, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('13:20'), weekday: true, court_id: 3, covid_slot: true},
{ time: Time.zone.parse('14:00'), weekday: true, court_id: 3, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('14:20'), weekday: true, court_id: 3, covid_slot: true},
{ time: Time.zone.parse('15:00'), weekday: true, court_id: 3, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('15:20'), weekday: true, court_id: 3, covid_slot: true},
{ time: Time.zone.parse('16:00'), weekday: true, court_id: 3, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('16:20'), weekday: true, court_id: 3, covid_slot: true},
{ time: Time.zone.parse('17:00'), weekday: true, court_id: 3, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('17:20'), weekday: true, court_id: 3, covid_slot: true},
{ time: Time.zone.parse('18:00'), weekday: true, court_id: 3, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('18:20'), weekday: true, court_id: 3, covid_slot: true},
{ time: Time.zone.parse('19:00'), weekday: true, court_id: 3, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('19:20'), weekday: true, court_id: 3, covid_slot: true},
{ time: Time.zone.parse('20:00'), weekday: true, court_id: 3, covid_slot: true, cleaning: true, bank_holiday: false},
{ time: Time.zone.parse('20:20'), weekday: true, court_id: 3, covid_slot: true, bank_holiday: false},
{ time: Time.zone.parse('21:00'), weekday: true, court_id: 3, covid_slot: true, cleaning: true, bank_holiday: false},
{ time: Time.zone.parse('21:20'), weekday: true, court_id: 3, covid_slot: true, bank_holiday: false},
{ time: Time.zone.parse('22:00'), weekday: true, court_id: 3, covid_slot: true, cleaning: true, bank_holiday: false},
{ time: Time.zone.parse('22:20'), weekday: true, court_id: 3, covid_slot: true, bank_holiday: false},
{ time: Time.zone.parse('23:00'), weekday: true, court_id: 3, covid_slot: true, cleaning: true, bank_holiday: false},

{ time: Time.zone.parse('12:30'), weekday: true, court_id: 4, covid_slot: true},
{ time: Time.zone.parse('13:10'), weekday: true, court_id: 4, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('13:30'), weekday: true, court_id: 4, covid_slot: true},
{ time: Time.zone.parse('14:10'), weekday: true, court_id: 4, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('14:30'), weekday: true, court_id: 4, covid_slot: true},
{ time: Time.zone.parse('15:10'), weekday: true, court_id: 4, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('15:30'), weekday: true, court_id: 4, covid_slot: true},
{ time: Time.zone.parse('16:10'), weekday: true, court_id: 4, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('16:30'), weekday: true, court_id: 4, covid_slot: true},
{ time: Time.zone.parse('17:10'), weekday: true, court_id: 4, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('17:30'), weekday: true, court_id: 4, covid_slot: true},
{ time: Time.zone.parse('18:10'), weekday: true, court_id: 4, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('18:30'), weekday: true, court_id: 4, covid_slot: true},
{ time: Time.zone.parse('19:10'), weekday: true, court_id: 4, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('19:30'), weekday: true, court_id: 4, covid_slot: true},
{ time: Time.zone.parse('20:10'), weekday: true, court_id: 4, covid_slot: true, cleaning: true, bank_holiday: false},
{ time: Time.zone.parse('20:30'), weekday: true, court_id: 4, covid_slot: true, bank_holiday: false},
{ time: Time.zone.parse('21:10'), weekday: true, court_id: 4, covid_slot: true, cleaning: true, bank_holiday: false},
{ time: Time.zone.parse('21:30'), weekday: true, court_id: 4, covid_slot: true, bank_holiday: false},
{ time: Time.zone.parse('22:10'), weekday: true, court_id: 4, covid_slot: true, cleaning: true, bank_holiday: false},
{ time: Time.zone.parse('22:30'), weekday: true, court_id: 4, covid_slot: true, bank_holiday: false},
{ time: Time.zone.parse('23:10'), weekday: true, court_id: 4, covid_slot: true, cleaning: true, bank_holiday: false},

{ time: Time.zone.parse('12:40'), weekday: true, court_id: 5, covid_slot: true},
{ time: Time.zone.parse('13:20'), weekday: true, court_id: 5, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('13:40'), weekday: true, court_id: 5, covid_slot: true},
{ time: Time.zone.parse('14:20'), weekday: true, court_id: 5, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('14:40'), weekday: true, court_id: 5, covid_slot: true},
{ time: Time.zone.parse('15:20'), weekday: true, court_id: 5, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('15:40'), weekday: true, court_id: 5, covid_slot: true},
{ time: Time.zone.parse('16:20'), weekday: true, court_id: 5, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('16:40'), weekday: true, court_id: 5, covid_slot: true},
{ time: Time.zone.parse('17:20'), weekday: true, court_id: 5, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('17:40'), weekday: true, court_id: 5, covid_slot: true},
{ time: Time.zone.parse('18:20'), weekday: true, court_id: 5, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('18:40'), weekday: true, court_id: 5, covid_slot: true},
{ time: Time.zone.parse('19:20'), weekday: true, court_id: 5, covid_slot: true, cleaning: true},
{ time: Time.zone.parse('19:40'), weekday: true, court_id: 5, covid_slot: true},
{ time: Time.zone.parse('20:20'), weekday: true, court_id: 5, covid_slot: true, cleaning: true, bank_holiday: false},
{ time: Time.zone.parse('20:40'), weekday: true, court_id: 5, covid_slot: true, bank_holiday: false},
{ time: Time.zone.parse('21:20'), weekday: true, court_id: 5, covid_slot: true, cleaning: true, bank_holiday: false},
{ time: Time.zone.parse('21:40'), weekday: true, court_id: 5, covid_slot: true, bank_holiday: false},
{ time: Time.zone.parse('22:20'), weekday: true, court_id: 5, covid_slot: true, cleaning: true, bank_holiday: false},
{ time: Time.zone.parse('22:40'), weekday: true, court_id: 5, covid_slot: true, bank_holiday: false},
{ time: Time.zone.parse('23:20'), weekday: true, court_id: 5, covid_slot: true, cleaning: true, bank_holiday: false},
])