Player.where(:first_name => 'Mark', :last_name => 'Williamson', :mobile => '07715 305225', :membership_number => 'C042', :membership_type_id => 1, email: 'markw@markwilliamsonweddings.com', :landline => '01670 505854', :admin => false ).first_or_create
Player.where(:first_name => 'David', :last_name => 'Smith', :mobile => '07980 500343', :membership_number => 'C046', :membership_type_id => '1', email: 'dbsmith2711@bt.com', :landline => '0191 4920641', :admin =>'false' ).first_or_create
Player.where(:first_name => 'John', :last_name => 'Smith', :mobile => '', :membership_number => 'C048', :membership_type_id => '1', email: '', :landline => '01670 817263', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Elizabeth', :last_name => 'Dodds', :mobile => '07711 887778', :membership_number => 'C049', :membership_type_id => '1', email: 'elizabethdodds@sky.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Christopher', :last_name => 'Appleby ', :mobile => '07590 692976', :membership_number => 'C050', :membership_type_id => '1', email: '', :landline => '0191 2892900', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Ian', :last_name => 'Clough', :mobile => '07702 553795', :membership_number => 'C054', :membership_type_id => '1', email: 'clough_ian@hotmail.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Peter', :last_name => 'Slaughter', :mobile => '07879 600905', :membership_number => 'C055', :membership_type_id => '1', email: 'pslaughter76@gmail.com', :landline => '0167 0815050', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Michael', :last_name => 'Slater', :mobile => '07772 906352', :membership_number => 'C068', :membership_type_id => '1', email: '', :landline => '01670 735458', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Henry', :last_name => 'Armstrong', :mobile => '07581 240261', :membership_number => 'Co037', :membership_type_id => '2', email: 'tyner55@hotmail.com', :landline => '0191 2664678', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Barbara', :last_name => 'Armstrong', :mobile => '07803 248399', :membership_number => 'Co038', :membership_type_id => '2', email: '', :landline => '0191 2664678', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Dawn', :last_name => 'Ward', :mobile => '', :membership_number => 'Co039', :membership_type_id => '2', email: '', :landline => '0191 2848293', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Glenn', :last_name => 'Ward', :mobile => '', :membership_number => 'Co040', :membership_type_id => '2', email: 'ward.gs@pg.com', :landline => '0191 2848293', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Sharron', :last_name => 'Mather', :mobile => '07962 184256', :membership_number => 'Co041', :membership_type_id => '2', email: 'sharronmather@blueyonder.co.uk', :landline => '0191 2096211', :admin =>'false' ).first_or_create
Player.where(:first_name => 'George', :last_name => 'Mather', :mobile => '', :membership_number => 'Co042', :membership_type_id => '2', email: '', :landline => '0191 2096211', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Alan', :last_name => 'Wall', :mobile => '07710 124412', :membership_number => 'Co049', :membership_type_id => '2', email: 'wall.alan76@gmail.com', :landline => '0191 2582734', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Janet', :last_name => 'Wall', :mobile => '07975 807280', :membership_number => 'Co050', :membership_type_id => '2', email: 'janwall.wall8@gmail.com', :landline => '0191 2582734', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Richard', :last_name => 'Routledge', :mobile => '07778 792288', :membership_number => 'Co051', :membership_type_id => '2', email: 'richard.routledge@talktalk.net', :landline => '0191 2401245', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Yvonne', :last_name => 'Routledge', :mobile => '07825 713113', :membership_number => 'Co052', :membership_type_id => '2', email: 'yvonne.routledge@dwp.gsi.gov.uk', :landline => '0191 2401245', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Stuart', :last_name => 'Varrall', :mobile => '07791 834890', :membership_number => 'Co053', :membership_type_id => '2', email: 'stuart@varrall.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Ruth', :last_name => 'Varrall', :mobile => '07754 295378', :membership_number => 'Co054', :membership_type_id => '2', email: 'ruth@varrall.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Dräger', :last_name => 'Dräger', :mobile => '', :membership_number => 'Corp01', :membership_type_id => '3', email: '', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Paul', :last_name => 'Millington', :mobile => '', :membership_number => 'F101', :membership_type_id => '4', email: '', :landline => '0191 2599770', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Gill', :last_name => 'Millington', :mobile => '', :membership_number => 'F102', :membership_type_id => '4', email: 'gillymilly@talktalk.net', :landline => '0191 2599770', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Sean', :last_name => 'Millington', :mobile => '07540 054548', :membership_number => 'F103', :membership_type_id => '4', email: '', :landline => '0191 2599770', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Lisa', :last_name => 'Millington', :mobile => '', :membership_number => 'F104', :membership_type_id => '4', email: '', :landline => '0191 2599770', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Paul', :last_name => 'Beecroft', :mobile => '07790 734560', :membership_number => 'F201', :membership_type_id => '4', email: 'beecroft907@btinternet.com', :landline => '0191 2376806', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Susan', :last_name => 'Beecroft', :mobile => '', :membership_number => 'F202', :membership_type_id => '4', email: 'sue.beecroft@dwp.gsi.gov.uk', :landline => '0191 2376806', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Lucy', :last_name => 'Beecroft', :mobile => '', :membership_number => 'F203', :membership_type_id => '4', email: 'beecroft907@btinternet.com', :landline => '0191 2376806', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Wayne', :last_name => 'Dobson', :mobile => '', :membership_number => 'F301', :membership_type_id => '4', email: 'w.dobson@blueyonder.co.uk', :landline => '0191 2803004', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Nicky', :last_name => 'Dobson', :mobile => '07958 006606', :membership_number => 'F302', :membership_type_id => '4', email: 'nicky.turnbull@ncl-coll.ac.uk', :landline => '0191 2803004', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Daisy', :last_name => 'Dobson', :mobile => '', :membership_number => 'F303', :membership_type_id => '4', email: 'nicky.turnbull@ncl-col.ax.uk', :landline => '0191 2803004', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Nathan', :last_name => 'Dobson', :mobile => '07731 753377', :membership_number => 'F304', :membership_type_id => '4', email: 'nathan_dobson@yahoo.co.uk', :landline => '0191 2803004', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Dave', :last_name => 'Todd', :mobile => '07842 820706', :membership_number => 'F401', :membership_type_id => '4', email: 'dtodd@toucansurf.com', :landline => '0191 2170358', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Alison', :last_name => 'Todd', :mobile => '07563 691204', :membership_number => 'F402', :membership_type_id => '4', email: 'dtodd@toucansurf.com', :landline => '0191 2170358', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Jamie', :last_name => 'Todd', :mobile => '07547 856123', :membership_number => 'F403', :membership_type_id => '4', email: 'dtodd@toucansurf.com', :landline => '0191 2170358', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Darren', :last_name => 'Lockwood', :mobile => '07935 122582', :membership_number => 'F501', :membership_type_id => '4', email: 'lockwood531@btinternet.com', :landline => '0191 2515103', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Beverley', :last_name => 'Lockwood', :mobile => '07858 240183', :membership_number => 'F502', :membership_type_id => '4', email: '', :landline => '0191 2515103', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Charlie', :last_name => 'Lockwood', :mobile => '07935 122582', :membership_number => 'F503', :membership_type_id => '4', email: '', :landline => '0191 2515103', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Lennox', :last_name => 'Lockwood', :mobile => '07935 122582', :membership_number => 'F504', :membership_type_id => '4', email: '', :landline => '0191 2515103', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Adam', :last_name => 'Bathgate', :mobile => '07949 229354', :membership_number => 'F601', :membership_type_id => '4', email: 'adam.bathgate@blueyonder.co.uk', :landline => '0191 2095287', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Deborah', :last_name => 'Bathgate', :mobile => '07949 229354', :membership_number => 'F602', :membership_type_id => '4', email: 'adam.bathgate@blueyonder.co.uk', :landline => '0191 2095287', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Steven', :last_name => 'Bathgate', :mobile => '', :membership_number => 'F603', :membership_type_id => '4', email: '', :landline => '0191 2095287', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Lois', :last_name => 'Bathgate', :mobile => '', :membership_number => 'F604', :membership_type_id => '4', email: '', :landline => '0191 2095287', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Kevin', :last_name => 'Wills', :mobile => '07768 061358', :membership_number => 'F701', :membership_type_id => '4', email: 'k.wills@hotmail.co.uk', :landline => '0191 2517876', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Judith', :last_name => 'Wills', :mobile => '', :membership_number => 'F702', :membership_type_id => '4', email: '', :landline => '0191 2517876', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Jamie', :last_name => 'Wills', :mobile => '', :membership_number => 'F703', :membership_type_id => '4', email: 'k.wills@hotmail.co.uk', :landline => '0191 2517876', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Matthew', :last_name => 'Wills', :mobile => '', :membership_number => 'F704', :membership_type_id => '4', email: 'k.wills@hotmail.co.uk', :landline => '0191 2517876', :admin =>'false' ).first_or_create
Player.where(:first_name => 'David', :last_name => 'Snedden', :mobile => '07515 571328', :membership_number => 'Gym05', :membership_type_id => '9', email: 'davesnedden@yahoo.co.uk', :landline => '0191 2169250', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Estelle', :last_name => 'Holland', :mobile => '07546 243045', :membership_number => 'Gym06', :membership_type_id => '9', email: 'estelle.holland@hotmail.co.uk', :landline => '0191 2537749', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Nathan', :last_name => 'Moholem', :mobile => '07783 179047', :membership_number => 'Gym07', :membership_type_id => '9', email: '', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Denise', :last_name => 'Bolt', :mobile => '07811 978443', :membership_number => 'Gym10', :membership_type_id => '9', email: 'DB002b8041@blueyonder.co.uk', :landline => '0191 2574857', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Sam', :last_name => 'Ward', :mobile => '', :membership_number => 'IS021', :membership_type_id => '6', email: '', :landline => '0191 2848293', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Ryder', :last_name => 'Buchanan', :mobile => '07540 116830', :membership_number => 'IS024', :membership_type_id => '6', email: 'ryderbuchanan@hotmail.co.uk', :landline => '0191 2513028', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Robert', :last_name => 'Bolt', :mobile => '07857 129471', :membership_number => 'IS039', :membership_type_id => '6', email: 'robertbolt@hotmail.co.uk', :landline => '0191 2574867', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Cameron', :last_name => 'Gunn', :mobile => '', :membership_number => 'IS043', :membership_type_id => '6', email: '', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Anthony', :last_name => 'Gunn', :mobile => '07898 710631', :membership_number => 'IS044', :membership_type_id => '6', email: 'anthonygunn1@hotmail.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Aimee Elen', :last_name => 'Cadwallader', :mobile => '07846 969371', :membership_number => 'IS045', :membership_type_id => '6', email: 'aimeegunn1@hotmail.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Josh', :last_name => 'Bell', :mobile => '07964 310541', :membership_number => 'IS046', :membership_type_id => '6', email: 'belza-93@live.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Liam', :last_name => 'Ferguson', :mobile => '07867 991192', :membership_number => 'IS048', :membership_type_id => '6', email: 'l.b.ferguson@hotmail.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Aleksis', :last_name => 'Martindale', :mobile => '07748 675279', :membership_number => 'IS050', :membership_type_id => '6', email: 'ak@bmakm.plus.com', :landline => '0191 2583218', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Katrina', :last_name => 'Martindale', :mobile => '17891 060615', :membership_number => 'IS051', :membership_type_id => '6', email: 'km@bmakm.plus.com', :landline => '0191 2583218', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Robert', :last_name => 'Miller', :mobile => '07930 664124', :membership_number => 'IS052', :membership_type_id => '6', email: 'r.miller.6@hotmail.com', :landline => '0191 2577935', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Sophie', :last_name => 'Conlon', :mobile => '07956 373989', :membership_number => 'IS053', :membership_type_id => '6', email: 'sophieconlon08@live.com', :landline => '0191 2636185', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Alison', :last_name => 'Carr', :mobile => '07890 864491', :membership_number => 'IS102', :membership_type_id => '6', email: 'alisoncarr@fsmail.net', :landline => '0191 2894742', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Alex', :last_name => 'Carr', :mobile => '', :membership_number => 'J002', :membership_type_id => '7', email: '', :landline => '0191 2894742', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Matthew', :last_name => 'Carr', :mobile => '', :membership_number => 'J003', :membership_type_id => '7', email: '', :landline => '0191 2894742', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Tom', :last_name => 'Walsh', :mobile => '', :membership_number => 'J007', :membership_type_id => '7', email: '', :landline => '0191 2570659', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Andrew', :last_name => 'Walsh', :mobile => '07553 933070', :membership_number => 'J008', :membership_type_id => '7', email: 'jlwalsh@talktalk.net', :landline => '0191 2570659', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Matthew', :last_name => 'Walsh', :mobile => '07896 330750', :membership_number => 'J009', :membership_type_id => '7', email: 'jlwalsh@talktalk.net', :landline => '0191 2570659', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Georgia', :last_name => 'Webster', :mobile => '07554 422091', :membership_number => 'J123', :membership_type_id => '7', email: '', :landline => '0191 4476982', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Amy', :last_name => 'Rowell', :mobile => '07908 610519', :membership_number => 'J124', :membership_type_id => '7', email: 'amy.rowell0845@gmail.com', :landline => '0191 5374195', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Emma', :last_name => 'Rowell', :mobile => '07415 862096', :membership_number => 'J125', :membership_type_id => '7', email: 'emma.rowell0853@gmail.com', :landline => '0191 5374195', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Molly', :last_name => 'O''Shannon', :mobile => '', :membership_number => 'J188', :membership_type_id => '7', email: 'norahp@hotmail.com', :landline => '0191 2666525', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Adam', :last_name => 'Robertson', :mobile => '', :membership_number => 'J193', :membership_type_id => '7', email: '', :landline => '0191 2801367', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Josef', :last_name => 'Scott', :mobile => '07772 147570', :membership_number => 'J203', :membership_type_id => '7', email: 'jayarrscott@hotmail.com', :landline => '0191 2903152', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Daniel', :last_name => 'Love', :mobile => '', :membership_number => 'J216', :membership_type_id => '7', email: '', :landline => '0191 2687663', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Nicholas', :last_name => 'McIntyre', :mobile => '', :membership_number => 'J241', :membership_type_id => '7', email: '', :landline => '0191 2511514', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Jake', :last_name => 'Slater', :mobile => '07772 906352', :membership_number => 'J242', :membership_type_id => '7', email: '', :landline => '01670 735458', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Jack', :last_name => 'Hearn', :mobile => '', :membership_number => 'J354', :membership_type_id => '7', email: '', :landline => '0191 2906021', :admin =>'false' ).first_or_create
Player.where(:first_name => 'James', :last_name => 'Waller', :mobile => '', :membership_number => 'J395', :membership_type_id => '7', email: '', :landline => '0191 2576945', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Katie', :last_name => 'Waller', :mobile => '', :membership_number => 'J396', :membership_type_id => '7', email: '', :landline => '0191 2576945', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Samantha', :last_name => 'Checkley', :mobile => '', :membership_number => 'J405', :membership_type_id => '7', email: '', :landline => '0191 2573145', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Mabel', :last_name => 'Harrington', :mobile => '', :membership_number => 'J406', :membership_type_id => '7', email: '', :landline => '0191 2853406', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Cameron', :last_name => 'Berry', :mobile => '', :membership_number => 'J411', :membership_type_id => '7', email: '', :landline => '0191 2530908', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Katy', :last_name => 'Albone', :mobile => '', :membership_number => 'J413', :membership_type_id => '7', email: '', :landline => '0191 2661571', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Emma Louise', :last_name => 'Bates', :mobile => '07957 023097', :membership_number => 'J414', :membership_type_id => '7', email: 'thebatesclan@msn.com', :landline => '0191 6604180', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Maya', :last_name => 'Dixon', :mobile => '07891 058884', :membership_number => 'J415', :membership_type_id => '7', email: '', :landline => '0191 2807295', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Nathan', :last_name => 'Wong', :mobile => '', :membership_number => 'J416', :membership_type_id => '7', email: '', :landline => '0019 1253074', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Thomas', :last_name => 'Wong', :mobile => '', :membership_number => 'J417', :membership_type_id => '7', email: '', :landline => '0019 1253074', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Callum', :last_name => 'Simpson', :mobile => '', :membership_number => 'J418', :membership_type_id => '7', email: '', :landline => '0191 2402592', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Cai', :last_name => 'Younger', :mobile => '07701 087965', :membership_number => 'J421', :membership_type_id => '7', email: 'cai.sj.younger@gmail.com', :landline => '0191 2170756', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Tegan', :last_name => 'Younger', :mobile => '07939 933266', :membership_number => 'J422', :membership_type_id => '7', email: 'teganyounger@talktalk.net', :landline => '0191 2170756', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Ross', :last_name => 'McLane', :mobile => '', :membership_number => 'J423', :membership_type_id => '7', email: '', :landline => '0192 2971169', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Olivia', :last_name => 'Douglas', :mobile => '07904 243015', :membership_number => 'J434', :membership_type_id => '7', email: '', :landline => '0191 2526151', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Liam', :last_name => 'Duncan-Kahn', :mobile => '07979 664960', :membership_number => 'J435', :membership_type_id => '7', email: 'libbykahn@talktalk.net', :landline => '0191 2367055', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Tom', :last_name => 'Cornell', :mobile => '07738 758650', :membership_number => 'J436', :membership_type_id => '7', email: 'julieccornell@msn.com', :landline => '0191 2171294', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Jude', :last_name => 'Mitcheson', :mobile => '07801 556418', :membership_number => 'J437', :membership_type_id => '7', email: 'mitchesoncolin@yahoo.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Lee', :last_name => 'Emerson', :mobile => '07551 903413', :membership_number => 'J438', :membership_type_id => '7', email: 'susanellis2@yahoo.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Thomas', :last_name => 'Middleton Jnr', :mobile => '', :membership_number => 'J439', :membership_type_id => '7', email: '', :landline => '0191 2702137', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Laura', :last_name => 'Neill', :mobile => '07962 428435', :membership_number => 'J441', :membership_type_id => '7', email: 'steveandnicolaneill@btinternet.com', :landline => '0167 0531005', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Daniel', :last_name => 'Neill', :mobile => '07962 428435', :membership_number => 'J442', :membership_type_id => '7', email: 'steveandnicolaneill@btinternet.com', :landline => '0167 0531005', :admin =>'false' ).first_or_create
Player.where(:first_name => 'William', :last_name => 'Gemmell', :mobile => '07817 279090', :membership_number => 'J443', :membership_type_id => '7', email: 'nicholasgemmell@o2.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Thomas', :last_name => 'Skelton', :mobile => '07825 417294', :membership_number => 'J445', :membership_type_id => '7', email: 'skelton50@gmail.com', :landline => '0191 2583296', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Emily', :last_name => 'King', :mobile => '07501 133624', :membership_number => 'J446', :membership_type_id => '7', email: 'andy.king@amec.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Amy', :last_name => 'Love', :mobile => '', :membership_number => 'J449', :membership_type_id => '7', email: '', :landline => '0191 2687663', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Charlie', :last_name => 'Took', :mobile => '', :membership_number => 'J450', :membership_type_id => '7', email: '', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Ben', :last_name => 'Evans', :mobile => '07526 363309', :membership_number => 'J452', :membership_type_id => '7', email: 'jons.email@btinternet.com', :landline => '0191 4201189', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Sam', :last_name => 'Evans', :mobile => '07526 363309', :membership_number => 'J453', :membership_type_id => '7', email: 'jons.email@btinternet.com', :landline => '0191 4201189', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Niamh', :last_name => 'Dallat', :mobile => '', :membership_number => 'J454', :membership_type_id => '7', email: '', :landline => '0191 2521190', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Rosa', :last_name => 'Hall', :mobile => '', :membership_number => 'J459', :membership_type_id => '7', email: 'helenbell@blueyonder.co.uk', :landline => '0191 2809217', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Ivon', :last_name => 'Holland', :mobile => '', :membership_number => 'J460', :membership_type_id => '7', email: 'estelle.holland@hotmail.co.uk', :landline => '0191 2537749', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Luke', :last_name => 'Myers', :mobile => '07414 694037', :membership_number => 'J461', :membership_type_id => '7', email: '', :landline => '0191 2911173', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Alex', :last_name => 'Manning', :mobile => '', :membership_number => 'J462', :membership_type_id => '7', email: '', :landline => '0191 2709027', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Cameron', :last_name => 'Ilderton', :mobile => '', :membership_number => 'J463', :membership_type_id => '7', email: '', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Catherine', :last_name => 'Scott', :mobile => '', :membership_number => 'J464', :membership_type_id => '7', email: '', :landline => '0191 2913623', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Ben', :last_name => 'King', :mobile => '07501 133624', :membership_number => 'J465', :membership_type_id => '7', email: 'andy.king@amec.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Emily', :last_name => 'Harrison', :mobile => '07808 538068', :membership_number => 'J466', :membership_type_id => '7', email: 'george.harrison@btinternet.com', :landline => '0191 2572349', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Daniel', :last_name => 'Harrison', :mobile => '', :membership_number => 'J467', :membership_type_id => '7', email: 'george.harrison@btinternet.com', :landline => '0191 2572349', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Steve', :last_name => 'Cubbins', :mobile => '07949 086158', :membership_number => 'LM007', :membership_type_id => '8', email: 'steve@cubbins.com', :landline => '0191 2912948', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Cy', :last_name => 'Dobson', :mobile => '', :membership_number => 'LM008', :membership_type_id => '8', email: '', :landline => '0191 2376921', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Alan', :last_name => 'Douglas', :mobile => '', :membership_number => 'LM009', :membership_type_id => '8', email: '', :landline => '0191 2851854', :admin =>'false' ).first_or_create
Player.where(:first_name => 'A', :last_name => 'Gilberg', :mobile => '', :membership_number => 'LM010', :membership_type_id => '8', email: '', :landline => '0191 2572841', :admin =>'false' ).first_or_create
Player.where(:first_name => 'A', :last_name => 'Gofton', :mobile => '', :membership_number => 'LM012', :membership_type_id => '8', email: '', :landline => '01665 589257', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Peter', :last_name => 'Grant', :mobile => '', :membership_number => 'LM013', :membership_type_id => '8', email: '', :landline => '0191 2576766', :admin =>'false' ).first_or_create
Player.where(:first_name => 'T', :last_name => 'Hart', :mobile => '', :membership_number => 'LM016', :membership_type_id => '8', email: '', :landline => '0193 773959', :admin =>'false' ).first_or_create
Player.where(:first_name => 'N', :last_name => 'Hewison', :mobile => '', :membership_number => 'LM018', :membership_type_id => '8', email: '', :landline => '0191 2512757', :admin =>'false' ).first_or_create
Player.where(:first_name => 'David', :last_name => 'Houston', :mobile => '', :membership_number => 'LM019', :membership_type_id => '8', email: '', :landline => '0191 2574859', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Francis', :last_name => 'Kidd', :mobile => '', :membership_number => 'LM020', :membership_type_id => '8', email: '', :landline => '0191 2528860', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Steve', :last_name => 'Laws', :mobile => '', :membership_number => 'LM022', :membership_type_id => '8', email: '', :landline => '0191 2573157', :admin =>'false' ).first_or_create
Player.where(:first_name => 'N', :last_name => 'Mathieson', :mobile => '', :membership_number => 'LM023', :membership_type_id => '8', email: '', :landline => '0191 2579617', :admin =>'false' ).first_or_create
Player.where(:first_name => 'L', :last_name => 'Myers', :mobile => '', :membership_number => 'LM024', :membership_type_id => '8', email: '', :landline => '0191 2534673', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Alan', :last_name => 'McWhinnie', :mobile => '', :membership_number => 'LM025', :membership_type_id => '8', email: '', :landline => '0191 2529321', :admin =>'false' ).first_or_create
Player.where(:first_name => 'L', :last_name => 'Paterson', :mobile => '', :membership_number => 'LM026', :membership_type_id => '8', email: '', :landline => '0191 2520742', :admin =>'false' ).first_or_create
Player.where(:first_name => 'G', :last_name => 'Taylor', :mobile => '', :membership_number => 'LM028', :membership_type_id => '8', email: '', :landline => '0191 2529983', :admin =>'false' ).first_or_create
Player.where(:first_name => 'C', :last_name => 'Thompson', :mobile => '', :membership_number => 'LM029', :membership_type_id => '8', email: '', :landline => '0191 2574397', :admin =>'false' ).first_or_create
Player.where(:first_name => 'W', :last_name => 'Thompson', :mobile => '', :membership_number => 'LM030', :membership_type_id => '8', email: '', :landline => '0191 2590217', :admin =>'false' ).first_or_create
Player.where(:first_name => 'D', :last_name => 'Waters', :mobile => '', :membership_number => 'LM034', :membership_type_id => '8', email: '', :landline => '0191 2570024', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Tom', :last_name => 'Waters', :mobile => '', :membership_number => 'LM035', :membership_type_id => '8', email: '', :landline => '0191 280 7498', :admin =>'false' ).first_or_create
Player.where(:first_name => 'J', :last_name => 'White', :mobile => '', :membership_number => 'LM036', :membership_type_id => '8', email: '', :landline => '0191 2523087', :admin =>'false' ).first_or_create
Player.where(:first_name => 'J', :last_name => 'Young', :mobile => '', :membership_number => 'LM037', :membership_type_id => '8', email: '', :landline => '0191 2578755', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Garry', :last_name => 'Burton', :mobile => '', :membership_number => 'LM038', :membership_type_id => '8', email: '', :landline => '0191 2595454', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Alan', :last_name => 'Johnsen', :mobile => '07505 092248', :membership_number => 'LM039', :membership_type_id => '8', email: 'alanjlpj@yahoo.co.uk', :landline => '0191 2962623', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Steve', :last_name => 'Bertenshaw', :mobile => '', :membership_number => 'NP016', :membership_type_id => '13', email: 'Bertenshaw1@hotmail.com', :landline => '0191 2591263', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Paul', :last_name => 'Tebble', :mobile => '', :membership_number => 'NP027', :membership_type_id => '13', email: '', :landline => '0191 2894633', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Ian', :last_name => 'Robertson', :mobile => '07871 163369', :membership_number => 'NP032', :membership_type_id => '13', email: '', :landline => '0191 2587571', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Stu', :last_name => 'Ellis', :mobile => '', :membership_number => 'NP036', :membership_type_id => '13', email: '', :landline => '0191 2575982', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Peter', :last_name => 'Forster', :mobile => '', :membership_number => 'NP044', :membership_type_id => '13', email: 'Mopeteforster@aol.com', :landline => '0191 2579667', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Trevor', :last_name => 'Wilkinson', :mobile => '07904 948912', :membership_number => 'NP045', :membership_type_id => '13', email: 'trevorwilki@yahoo.co.uk', :landline => '0191 2623278', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Milton', :last_name => 'Stonebanks', :mobile => '07814 087457', :membership_number => 'NP050', :membership_type_id => '13', email: 'mstonebanks@blueyonder.co.uk', :landline => '0191 2577894', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Richard', :last_name => 'Scott', :mobile => '', :membership_number => 'NP063', :membership_type_id => '13', email: '', :landline => '0191 2576062', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Shaun', :last_name => 'Dunn', :mobile => '07774 914933', :membership_number => 'NP094', :membership_type_id => '13', email: 'shaun@shaundunn.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Jenny', :last_name => 'Ellis', :mobile => '', :membership_number => 'NP102', :membership_type_id => '13', email: '', :landline => '0191 2575982', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Robert', :last_name => 'Davis', :mobile => '', :membership_number => 'NP174', :membership_type_id => '13', email: '', :landline => '0191 2578526', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Arthur', :last_name => 'Daniels', :mobile => '', :membership_number => 'NP188', :membership_type_id => '13', email: '', :landline => '0191 2571930', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Arne', :last_name => 'Pedersen', :mobile => '', :membership_number => 'NP196', :membership_type_id => '13', email: 'norahp@hotmail.com', :landline => '0191 2666525', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Ken', :last_name => 'Brown', :mobile => '', :membership_number => 'NP224', :membership_type_id => '13', email: 'kennethbrown@sky.com', :landline => '0191 2961720', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Michelle', :last_name => 'Whitworth', :mobile => '', :membership_number => 'NP226', :membership_type_id => '13', email: 'mitchw@blueyonder.co.uk', :landline => '0191 2614237', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Alan', :last_name => 'Brookes', :mobile => '', :membership_number => 'NP245', :membership_type_id => '13', email: 'brookesfamily@hotmail.com', :landline => '0191 2895126', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Pat', :last_name => 'Stanley', :mobile => '07530 844163', :membership_number => 'NP246', :membership_type_id => '13', email: 'patstanley@talktalk.net', :landline => '0191 2570965', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Iain', :last_name => 'Simpson', :mobile => '', :membership_number => 'NP249', :membership_type_id => '13', email: 'iain@the_simpsons.fslight.co.uk', :landline => '0191 2584800', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Patrick', :last_name => 'Candon', :mobile => '07889 972279', :membership_number => 'NP250', :membership_type_id => '13', email: 'pat@candon.co.uk', :landline => '0191 2580952', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Dave', :last_name => 'Smith', :mobile => '', :membership_number => 'NP251', :membership_type_id => '13', email: '', :landline => '0191 2579389', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Paul', :last_name => 'Telford', :mobile => '', :membership_number => 'NP252', :membership_type_id => '13', email: 'paul.telford@talktalk.net', :landline => '0191 2524011', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Harry', :last_name => 'Wilkinson', :mobile => '', :membership_number => 'NP253', :membership_type_id => '13', email: '', :landline => '0191 2620557', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Derek', :last_name => 'Carpenter', :mobile => '07768 834856', :membership_number => 'NP255', :membership_type_id => '13', email: '', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'William', :last_name => 'Mankin', :mobile => '', :membership_number => 'NP261', :membership_type_id => '13', email: '', :landline => '0191 2893243', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Derek', :last_name => 'Callaghan', :mobile => '07866 255289', :membership_number => 'NP266', :membership_type_id => '13', email: 'calamity1cal@aol.com', :landline => '0191 2570760', :admin =>'false' ).first_or_create
Player.where(:first_name => 'John', :last_name => 'Laidler', :mobile => '', :membership_number => 'NP270', :membership_type_id => '13', email: '', :landline => '0191 2573257', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Kevin', :last_name => 'Lowery', :mobile => '07775 630961', :membership_number => 'NP271', :membership_type_id => '13', email: 'kevinlowery@hertel.co.uk', :landline => '0191 2624487', :admin =>'false' ).first_or_create
Player.where(:first_name => 'John', :last_name => 'Guthrie', :mobile => '', :membership_number => 'NP274', :membership_type_id => '13', email: '', :landline => '0191 2535982', :admin =>'false' ).first_or_create
Player.where(:first_name => 'William', :last_name => 'Tindle', :mobile => '', :membership_number => 'NP275', :membership_type_id => '13', email: '', :landline => '0191 2577816', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Lesley', :last_name => 'Barnett', :mobile => '', :membership_number => 'NP276', :membership_type_id => '13', email: '', :landline => '0191 2521631', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Irene', :last_name => 'Wharton', :mobile => '07904 453772', :membership_number => 'NP279', :membership_type_id => '13', email: '', :landline => '0191 2532779', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Bill', :last_name => 'Brotherton', :mobile => '', :membership_number => 'NP280', :membership_type_id => '13', email: '', :landline => '0191 2950594', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Maureen', :last_name => 'Hancock', :mobile => '', :membership_number => 'NP283', :membership_type_id => '13', email: '', :landline => '0191 2585373', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Brian', :last_name => 'Armstrong', :mobile => '', :membership_number => 'NP285', :membership_type_id => '13', email: '', :landline => '0191 2515414', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Elinor', :last_name => 'Armstrong', :mobile => '', :membership_number => 'NP286', :membership_type_id => '13', email: '', :landline => '0191 2515414', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Fiona', :last_name => 'Simpson', :mobile => '07790 703832', :membership_number => 'NP288', :membership_type_id => '13', email: 'fionamsimpson@yahoo.co.uk', :landline => '0191 2402592', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Ailsa', :last_name => 'Simpson', :mobile => '', :membership_number => 'NP289', :membership_type_id => '13', email: '', :landline => '0191 2402492', :admin =>'false' ).first_or_create
Player.where(:first_name => 'David', :last_name => 'Favour', :mobile => '07808 824663', :membership_number => 'NP292', :membership_type_id => '13', email: 'david.favour@btinternet.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Keith', :last_name => 'Tait', :mobile => '07754 467791', :membership_number => 'NP381', :membership_type_id => '13', email: 'kdtait@blueyonder.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Keith', :last_name => 'Appleby ', :mobile => '07940 782187', :membership_number => 'NP927', :membership_type_id => '13', email: '', :landline => '0191 2573286', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Marty', :last_name => 'Hoult', :mobile => '07768 376022', :membership_number => 'NP960', :membership_type_id => '13', email: '', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Rev Andrew', :last_name => 'Beeston', :mobile => '', :membership_number => 'R041', :membership_type_id => '10', email: '', :landline => '0191 2573331', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Sylvia', :last_name => 'Wilson', :mobile => '', :membership_number => 'R042', :membership_type_id => '10', email: 'sylviawilson1@live.co.uk', :landline => '0191 2531402', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Charles', :last_name => 'Goring', :mobile => '07785 576196', :membership_number => 'R043', :membership_type_id => '10', email: 'charles.goring@btinternet.com', :landline => '0191 2523702', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Ash', :last_name => 'Fox', :mobile => '07985 955777', :membership_number => 'R049', :membership_type_id => '10', email: 'ashfox4@googlemail.com', :landline => '0191 2913459', :admin =>'false' ).first_or_create
Player.where(:first_name => 'David', :last_name => 'Dolman', :mobile => '', :membership_number => 'R050', :membership_type_id => '10', email: 'david.dolman@hotmail.com', :landline => '0191 2570046', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Paul', :last_name => 'Athey', :mobile => '07974 019635', :membership_number => 'R051', :membership_type_id => '10', email: 'paulathey360@hotmail.com', :landline => '0191 2528080', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Kevin', :last_name => 'Bolt', :mobile => '07722 243769', :membership_number => 'R052', :membership_type_id => '10', email: 'DB002b8041@blueyonder.co.uk', :landline => '0191 2574867', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Angela', :last_name => 'McGhee', :mobile => '07789 900359', :membership_number => 'R053', :membership_type_id => '10', email: 'angela@trinityfs.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Aidan', :last_name => 'Flint', :mobile => '07449 303884', :membership_number => 'R054', :membership_type_id => '10', email: 'afgeologic@gmail.com', :landline => '0191 2517598', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Dean', :last_name => 'Hogarty', :mobile => '07796 008051', :membership_number => 'R055', :membership_type_id => '10', email: 'deanhogarty@gmail.com', :landline => '0191 2590551', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Keith', :last_name => 'Watson', :mobile => '', :membership_number => 'R056', :membership_type_id => '10', email: 'keithkwatson@aol.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Stephon', :last_name => 'Linsley', :mobile => '', :membership_number => 'R057', :membership_type_id => '10', email: 'steve.linsley@dwp.gov.uk', :landline => '0191 2687112', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Kevin', :last_name => 'Hogarty', :mobile => '', :membership_number => 'R058', :membership_type_id => '10', email: '', :landline => '0191 2590551', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Geoff', :last_name => 'Brindle', :mobile => '', :membership_number => 'R059', :membership_type_id => '10', email: 'brindlegeoff@hotmail.com', :landline => '0191 2092097', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Colin', :last_name => 'Campbell', :mobile => '07500 089789', :membership_number => 'R061', :membership_type_id => '10', email: 'col.campbell@accenture.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Chris', :last_name => 'Bradley', :mobile => '', :membership_number => 'R062', :membership_type_id => '10', email: '', :landline => '0191 4165075', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Marc', :last_name => 'Mawson', :mobile => '07808 646818', :membership_number => 'R063', :membership_type_id => '10', email: 'marc.mawson@gmail.com', :landline => '0191 4104153', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Jack', :last_name => 'Foster', :mobile => '', :membership_number => 'R064', :membership_type_id => '10', email: '', :landline => '0191 2533631', :admin =>'false' ).first_or_create
Player.where(:first_name => 'James', :last_name => 'McMichael', :mobile => '07834 986287', :membership_number => 'R065', :membership_type_id => '10', email: 'james.mcmichael@outlook.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Steve', :last_name => 'Taylor', :mobile => '07879 400662', :membership_number => 'R066', :membership_type_id => '10', email: 'steve.c.taylor@btinternet.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Carol', :last_name => 'Liddle', :mobile => '', :membership_number => 'R072', :membership_type_id => '10', email: '', :landline => '0191 2523694', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Miriam', :last_name => 'Evans', :mobile => '07723 051993', :membership_number => 'R073', :membership_type_id => '10', email: 'mi24794@yahoo.co.uk', :landline => '0191 2366215', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Anthony', :last_name => 'Worrall', :mobile => '07967 817768', :membership_number => 'R074', :membership_type_id => '10', email: 'anth.worrall@blueyonder.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Charlotte', :last_name => 'Swaddle', :mobile => '07905 925220', :membership_number => 'R076', :membership_type_id => '10', email: 'cswaddlee@yahoo.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Chris', :last_name => 'McLane', :mobile => '', :membership_number => 'R975', :membership_type_id => '10', email: 'chris.mclane@openwork.co.uk', :landline => '0191 2971169', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Tony', :last_name => 'Guy', :mobile => '07894 562528', :membership_number => 'S005', :membership_type_id => '11', email: 'tonytiger352003@yahoo.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Russell', :last_name => 'Hunter', :mobile => '07963 940557', :membership_number => 'S009', :membership_type_id => '11', email: 'russellhunter@hotmail.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Ross', :last_name => 'Mazzucchi', :mobile => '', :membership_number => 'S014', :membership_type_id => '11', email: 'rossmazzucchi@hotmail.com', :landline => '0191 2902204', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Michelle', :last_name => 'Proctor', :mobile => '07903 030753', :membership_number => 'S022', :membership_type_id => '11', email: '', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Steve', :last_name => 'Carney', :mobile => '07595 205302', :membership_number => 'S025', :membership_type_id => '11', email: 'stephencarney@blueyonder.co.uk', :landline => '0191 2912983', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Paul', :last_name => 'Dunn', :mobile => '07831 382354', :membership_number => 'S026', :membership_type_id => '11', email: 'pd@paul-dunn.co.uk', :landline => '0191 2595622', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Tim', :last_name => 'Mazzucchi', :mobile => '07985 563027', :membership_number => 'S031', :membership_type_id => '11', email: 'tim.mazzucchi@dwp.gis.gov.uk', :landline => '0191 2902204', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Chris', :last_name => 'Waller', :mobile => '07969 924368', :membership_number => 'S054', :membership_type_id => '11', email: 'carolewaller@sky.com', :landline => '0191 2576945', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Malcolm', :last_name => 'Chapman', :mobile => '', :membership_number => 'S091', :membership_type_id => '11', email: '', :landline => '0191 2513116', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Allan', :last_name => 'Charlton', :mobile => '07905 124858', :membership_number => 'S093', :membership_type_id => '11', email: 'acne10863@blueyonder.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Maurice', :last_name => 'Cliff', :mobile => '07738 788908', :membership_number => 'S100', :membership_type_id => '11', email: 'Mauricecliff@googlemail.com', :landline => '0191 2664959', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Nick', :last_name => 'Hunter', :mobile => '07854 252816', :membership_number => 'S101', :membership_type_id => '11', email: 'jwootle@googlemail.com', :landline => '0191 2535241', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Josh', :last_name => 'Gebhard', :mobile => '07827 322337', :membership_number => 'S107', :membership_type_id => '11', email: 'joshgebhard@hotmail.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'David', :last_name => 'Toole', :mobile => '', :membership_number => 'S118', :membership_type_id => '11', email: 'davidtoole43@hotmail.com', :landline => '0191 4016800', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Nick', :last_name => 'Hale', :mobile => '07738 858501', :membership_number => 'S119', :membership_type_id => '11', email: 'nicholas.hale@gmail.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Colin', :last_name => 'McNestrie', :mobile => '07917 358361', :membership_number => 'S123', :membership_type_id => '11', email: '', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Martin', :last_name => 'Kellaway', :mobile => '07771 862616', :membership_number => 'S124', :membership_type_id => '11', email: 'mkyne07839@blueyonder.co.uk', :landline => '0191 2520455', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Kevin', :last_name => 'Jackson', :mobile => '07540 697524', :membership_number => 'S125', :membership_type_id => '11', email: 'kevjackson_24@hotmail.co.uk', :landline => '0191 2901946', :admin =>'false' ).first_or_create
Player.where(:first_name => 'David', :last_name => 'Fenwick', :mobile => '07946 543711', :membership_number => 'S126', :membership_type_id => '11', email: 'dfenwick@lineone.net', :landline => '0191 2522573', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Alec', :last_name => 'Russell', :mobile => '07817 654182', :membership_number => 'S138', :membership_type_id => '11', email: '', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Keith', :last_name => 'Shannon', :mobile => '07725 057371', :membership_number => 'S144', :membership_type_id => '11', email: 'keith.shannon@btinternet.com', :landline => '0191 2377793', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Dave', :last_name => 'Wood', :mobile => '07970 902218', :membership_number => 'S149', :membership_type_id => '11', email: '', :landline => '0191 2528682', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Gary', :last_name => 'Eden', :mobile => '07949 083534', :membership_number => 'S151', :membership_type_id => '11', email: 'footandmouth.ga@blueyonder.co.uk', :landline => '0191 2972347', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Keith', :last_name => 'Woods', :mobile => '07709 708229', :membership_number => 'S158', :membership_type_id => '11', email: '', :landline => '0191 2517022', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Robert', :last_name => 'Scott', :mobile => '07790 686053', :membership_number => 'S159', :membership_type_id => '11', email: 'jayarrscott@hotmail.com', :landline => '0191 2583984', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Edward', :last_name => 'Henein', :mobile => '07966 230511', :membership_number => 'S175', :membership_type_id => '11', email: '', :landline => '0191 2537478', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Stephen', :last_name => 'Cruz', :mobile => '07956 356363', :membership_number => 'S179', :membership_type_id => '11', email: 'steveamanda@blueyonder.co.uk', :landline => '0191 2535882', :admin =>'false' ).first_or_create
Player.where(:first_name => 'John', :last_name => 'Gallagher', :mobile => '07982 242864', :membership_number => 'S192', :membership_type_id => '11', email: '23johng@gmail.com', :landline => '0191 2573537', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Robin', :last_name => 'Gunn', :mobile => '', :membership_number => 'S197', :membership_type_id => '11', email: '', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'John', :last_name => 'Thompson', :mobile => '07968 483977', :membership_number => 'S213', :membership_type_id => '11', email: 'thompson650@hotmail.com', :landline => '0191 2160193', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Chris', :last_name => 'Thompson', :mobile => '07958 006523', :membership_number => 'S214', :membership_type_id => '11', email: 'thompson887@btinternet.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Tim', :last_name => 'Shield', :mobile => '07748 268486', :membership_number => 'S233', :membership_type_id => '11', email: 'tim_shield@talktalk.net', :landline => '0191 2570965', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Robert', :last_name => 'Brown', :mobile => '07837 219374', :membership_number => 'S245', :membership_type_id => '11', email: 'robbo_11r@hotmail.com', :landline => '0191 2634950', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Chris', :last_name => 'Potts', :mobile => '07825 528289', :membership_number => 'S246', :membership_type_id => '11', email: 'k2.calling@yahoo.co.uk', :landline => '0191 2525901', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Guy', :last_name => 'Eniona', :mobile => '07806 796134', :membership_number => 'S247', :membership_type_id => '11', email: 'guyalbatrossin@hotmail.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Alan', :last_name => 'Love', :mobile => '07500 082259', :membership_number => 'S248', :membership_type_id => '11', email: '', :landline => '0191 2687663', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Cait', :last_name => 'Foley', :mobile => '07786 393260', :membership_number => 'S265', :membership_type_id => '11', email: 'cait_foley@yahoo.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Scott', :last_name => 'McKay', :mobile => '07702 508675', :membership_number => 'S266', :membership_type_id => '11', email: 'scottmack@btconnect.com', :landline => '0191 2901367', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Mick', :last_name => 'Kennedy', :mobile => '07711 756419', :membership_number => 'S267', :membership_type_id => '11', email: '', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'William', :last_name => 'Maloney', :mobile => '07986 663971', :membership_number => 'S270', :membership_type_id => '11', email: 'william.maloney@ncl.ac.uk', :landline => '0191 2523102', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Paul', :last_name => 'Newton', :mobile => '07957 253996', :membership_number => 'S274', :membership_type_id => '11', email: 'dpn35@aol.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'John', :last_name => 'Hearl', :mobile => '07763 029591', :membership_number => 'S275', :membership_type_id => '11', email: 'jonathan.hearl@blueyonder.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Ron', :last_name => 'Grant', :mobile => '', :membership_number => 'S276', :membership_type_id => '11', email: '', :landline => '0191 2341018', :admin =>'false' ).first_or_create
Player.where(:first_name => 'John', :last_name => 'Liddle', :mobile => '07909 103142', :membership_number => 'S278', :membership_type_id => '11', email: 'johnliddle1357789@yahoo.co.uk', :landline => '0191 2523694', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Peter', :last_name => 'Fargher', :mobile => '07824 531408', :membership_number => 'S279', :membership_type_id => '11', email: 'pfargher@yahoo.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Mark', :last_name => 'Humphreys', :mobile => '07715 321767', :membership_number => 'S288', :membership_type_id => '11', email: '', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'George', :last_name => 'Harrison', :mobile => '07777 628289', :membership_number => 'S289', :membership_type_id => '11', email: 'george.harrison@btinternet.com', :landline => '0191 2572349', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Margaret', :last_name => 'Algar', :mobile => '07792 311348', :membership_number => 'S309', :membership_type_id => '11', email: '', :landline => '0191 2592035', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Ray', :last_name => 'Raffle', :mobile => '07790 438612', :membership_number => 'S316', :membership_type_id => '11', email: 'Rayraffle@talktalk.net', :landline => '01670 366324', :admin =>'false' ).first_or_create
Player.where(:first_name => 'David', :last_name => 'Sundin', :mobile => '07850 637766', :membership_number => 'S325', :membership_type_id => '11', email: 'd.sundin@blueyonder.co.uk', :landline => '0191 4207325', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Norman', :last_name => 'Orange', :mobile => '07850 567365', :membership_number => 'S333', :membership_type_id => '11', email: 'normanorange@btinternet.com', :landline => '0191 2374291', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Lee', :last_name => 'Campbell', :mobile => '07517 353161', :membership_number => 'S344', :membership_type_id => '11', email: 'leecampbell79@hotmail.com', :landline => '0191 2682599', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Louise', :last_name => 'Robertson', :mobile => '07985 525149', :membership_number => 'S345', :membership_type_id => '11', email: 'louiser@hadaway.co.uk', :landline => '0191 2801367', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Mark', :last_name => 'Thompson', :mobile => '07594 350434', :membership_number => 'S357', :membership_type_id => '11', email: 'marknicholasthompson@me.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Raymond', :last_name => 'Thompson', :mobile => '07815 528872', :membership_number => 'S358', :membership_type_id => '11', email: '', :landline => '0191 2960314', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Daniel', :last_name => 'Wilson', :mobile => '07584 088626', :membership_number => 'S359', :membership_type_id => '11', email: 'danielwilson771@gmail.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Thomas', :last_name => 'Allan', :mobile => '07803 051803', :membership_number => 'S360', :membership_type_id => '11', email: 'tom.allan2@gmail.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Jeremy', :last_name => 'French', :mobile => '07886 899643', :membership_number => 'S361', :membership_type_id => '11', email: 'jeremyjfrench@hotmail.com', :landline => '0191 2537698', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Charlotte', :last_name => 'Osborn', :mobile => '07957 367457', :membership_number => 'S379', :membership_type_id => '11', email: 'ceosborn@mail.com', :landline => '0191 2739795', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Michael', :last_name => 'Sheldon', :mobile => '', :membership_number => 'S386', :membership_type_id => '11', email: 'micksheldon@hotmail.com', :landline => '0191 2572020', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Tom', :last_name => 'Mulligan', :mobile => '07711 309977', :membership_number => 'S389', :membership_type_id => '11', email: '', :landline => '0191 2750926', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Chris', :last_name => 'Checkley', :mobile => '', :membership_number => 'S403', :membership_type_id => '11', email: 'cheorley-chris@yahoo.co.uk', :landline => '0191 2573145', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Nick', :last_name => 'Gemmell', :mobile => '07817 279090', :membership_number => 'S404', :membership_type_id => '11', email: 'nicholasgemmell@o2.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'James', :last_name => 'Stewart', :mobile => '07855 392385', :membership_number => 'S405', :membership_type_id => '11', email: 'james.stewart1452@hotmail.com', :landline => '0191 6590713', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Kevin', :last_name => 'Vallely', :mobile => '07774 980567', :membership_number => 'S408', :membership_type_id => '11', email: 'maryvallely@aol.com', :landline => '0191 2344591', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Dennis', :last_name => 'Knight', :mobile => '07763 183736', :membership_number => 'S409', :membership_type_id => '11', email: 'dkmidblu@aol.com', :landline => '0191 2622442', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Simon', :last_name => 'Kellett', :mobile => '07977 452704', :membership_number => 'S423', :membership_type_id => '11', email: 'skellettor@hotmail.com', :landline => '0191 2891509', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Steven', :last_name => 'Jacobs', :mobile => '07841 524469', :membership_number => 'S424', :membership_type_id => '11', email: 'jacobs124@sky.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Bob', :last_name => 'Graham', :mobile => '07779 428108', :membership_number => 'S427', :membership_type_id => '11', email: '', :landline => '0191 2631718', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Barry', :last_name => 'Watson', :mobile => '07922 044813', :membership_number => 'S435', :membership_type_id => '11', email: 'cwatsits@aol.com', :landline => '0191 2528447', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Ryan', :last_name => 'Dallat', :mobile => '07446 879969', :membership_number => 'S454', :membership_type_id => '11', email: 'ryandallat@hotmail.com', :landline => '0191 2521190', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Gill', :last_name => 'Mason', :mobile => '07939 614423', :membership_number => 'S462', :membership_type_id => '11', email: 'gillmason@blueyonder.co.uk', :landline => '0191 2903405', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Terry', :last_name => 'Smart ', :mobile => '07894 639904', :membership_number => 'S496', :membership_type_id => '11', email: 'terry@flynortheast.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'John', :last_name => 'Walsh', :mobile => '07847 141133', :membership_number => 'S525', :membership_type_id => '11', email: 'jlwalsh@talktalk.net', :landline => '0191 2570659', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Chris', :last_name => 'Beldon', :mobile => '07759 699692', :membership_number => 'S531', :membership_type_id => '11', email: 'chrisbeldon@hotmail.com', :landline => '0191 2980999', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Nick', :last_name => 'Cubley', :mobile => '07532 090609', :membership_number => 'S532', :membership_type_id => '11', email: 'nickcubley@yahoo.co.uk', :landline => '0191 2170021', :admin =>'false' ).first_or_create
Player.where(:first_name => 'David', :last_name => 'Wilson', :mobile => '07925 679587', :membership_number => 'S543', :membership_type_id => '11', email: 'david131wilson@btinternet.com', :landline => '0191 3858112', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Martin', :last_name => 'Inskip', :mobile => '07974 444813', :membership_number => 'S560', :membership_type_id => '11', email: '', :landline => '0191 2575037', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Doug', :last_name => 'Watt', :mobile => '07913 008729', :membership_number => 'S578', :membership_type_id => '11', email: '', :landline => '0191 2521951', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Steve', :last_name => 'Brown', :mobile => '07724 010210', :membership_number => 'S579', :membership_type_id => '11', email: '', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Nick', :last_name => 'Thornton', :mobile => '07834 827545', :membership_number => 'S580', :membership_type_id => '11', email: 'nickthornton1978@live.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'John', :last_name => 'McLean', :mobile => '07749 709844', :membership_number => 'S581', :membership_type_id => '11', email: 'john.mclean@uk-cpi.com', :landline => '0191 2628068', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Stan', :last_name => 'Taylor', :mobile => '07710 670349', :membership_number => 'S583', :membership_type_id => '11', email: 'stan.taylor@mckechnies.co.uk', :landline => '0191 2577457', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Jim', :last_name => 'Allen', :mobile => '07794 596539', :membership_number => 'S607', :membership_type_id => '11', email: 'jim.allen@svq.org.uk', :landline => '0191 2913498', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Dennis', :last_name => 'Stewart', :mobile => '07802 184315', :membership_number => 'S608', :membership_type_id => '11', email: 'denboy740@hotmail.com', :landline => '0191 2518225', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Norman', :last_name => 'Hope', :mobile => '07940 653603', :membership_number => 'S643', :membership_type_id => '11', email: 'metronrock@googlemail.com', :landline => '0191 2868386', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Steven', :last_name => 'Carlile', :mobile => '', :membership_number => 'S692', :membership_type_id => '11', email: '', :landline => '0191 2522307', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Andy', :last_name => 'King', :mobile => '07501 133624', :membership_number => 'S713', :membership_type_id => '11', email: 'kinga@entecuk.co.uk', :landline => '0191 2537357', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Norah', :last_name => 'Pedersen', :mobile => '07711 845154', :membership_number => 'S734', :membership_type_id => '11', email: 'norahp@hotmail.com', :landline => '0191 2666525', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Jeff', :last_name => 'Legg', :mobile => '07905 296997', :membership_number => 'S763', :membership_type_id => '11', email: 'jeff.legg@yahoo.co.uk', :landline => '0191 2901096', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Marty', :last_name => 'Allen', :mobile => '07753 949876', :membership_number => 'S775', :membership_type_id => '11', email: 'matin.j.allen@openreach.co.uk', :landline => '0191 2524717', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Allan', :last_name => 'Green', :mobile => '07770 917797', :membership_number => 'S780', :membership_type_id => '11', email: 'agreen@globalskm.com', :landline => '0191 2150220', :admin =>'false' ).first_or_create
Player.where(:first_name => 'David', :last_name => 'Armstrong', :mobile => '', :membership_number => 'S796', :membership_type_id => '11', email: '', :landline => '01670 716603', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Seamus', :last_name => 'McCallion', :mobile => '07775 933437', :membership_number => 'S801', :membership_type_id => '11', email: '', :landline => '0191 2576656', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Gordon', :last_name => 'Horsley', :mobile => '07776 138537', :membership_number => 'S811', :membership_type_id => '11', email: 'gordon@dieform.fsnet.co.uk', :landline => '0191 2523676', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Paul', :last_name => 'Easton', :mobile => '07957 823896', :membership_number => 'S812', :membership_type_id => '11', email: 'pauleaston@blueyonder.co.uk', :landline => '0191 2523657', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Dave', :last_name => 'Tait', :mobile => '07828 008067', :membership_number => 'S816', :membership_type_id => '11', email: 'taitdave@msn.com', :landline => '0191 2895225', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Louise', :last_name => 'Tupling', :mobile => '07942 703739', :membership_number => 'S817', :membership_type_id => '11', email: 'L.tupling@btinternet.com', :landline => '0191 2809339', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Geoff', :last_name => 'Mason', :mobile => '', :membership_number => 'S845', :membership_type_id => '11', email: 'massagmm@yahoo.co.uk', :landline => '0191 2914298', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Tony', :last_name => 'Crilley', :mobile => '07951 853610', :membership_number => 'S847', :membership_type_id => '11', email: 'tlc-nufc@blueyonder.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Colin', :last_name => 'Barrass', :mobile => '07903 086045', :membership_number => 'S848', :membership_type_id => '11', email: 'barrass.colin@hotmail.com', :landline => '0191 2701699', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Michael', :last_name => 'McIntyre', :mobile => '07811 348126', :membership_number => 'S852', :membership_type_id => '11', email: 'Mmcintyre@hotfreeze.org.uk', :landline => '0191 2511514', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Craig', :last_name => 'Taylor', :mobile => '07986 297739', :membership_number => 'S861', :membership_type_id => '11', email: 'c.t@blueyonder.co.uk', :landline => '0191 2803265', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Ray', :last_name => 'Rycroft', :mobile => '07584 994826', :membership_number => 'S865', :membership_type_id => '11', email: 'rayrycroft@gmail.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Paul', :last_name => 'Albone', :mobile => '07538 343168', :membership_number => 'S872', :membership_type_id => '11', email: 'paulalbone@blueyonder.co.uk', :landline => '0191 2661571', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Stu', :last_name => 'Bell', :mobile => '07985 110302', :membership_number => 'S873', :membership_type_id => '11', email: '', :landline => '0191 2803308', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Chris', :last_name => 'Chapman', :mobile => '07795 163059', :membership_number => 'S874', :membership_type_id => '11', email: 'chrischapman1612@googlemail.com', :landline => '0191 2159368', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Jon', :last_name => 'Evans', :mobile => '07526 363309', :membership_number => 'S875', :membership_type_id => '11', email: 'jons.email@btinternet.com', :landline => '0191 4201189', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Mel', :last_name => 'Hammond', :mobile => '07727 199839', :membership_number => 'S879', :membership_type_id => '11', email: 'melhammond160@hotmail.com', :landline => '0191 2625848', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Fred', :last_name => 'Iredale', :mobile => '07768 634709', :membership_number => 'S880', :membership_type_id => '11', email: 'freddieboy49@live.co.uk', :landline => '0191 2518042', :admin =>'false' ).first_or_create
Player.where(:first_name => 'David', :last_name => 'Rowland', :mobile => '07802 714060', :membership_number => 'S892', :membership_type_id => '11', email: 'david.rowland3@sky.com', :landline => '0191 2515360', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Doug', :last_name => 'Nicholson ', :mobile => '07801 487939', :membership_number => 'S896', :membership_type_id => '11', email: 'nicholsonbutcher@btconnect.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Philip', :last_name => 'Warwick', :mobile => '07808 826863', :membership_number => 'S897', :membership_type_id => '11', email: 'philip.warwick@siemens.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Eric', :last_name => 'Mok', :mobile => '07979 913238', :membership_number => 'S901', :membership_type_id => '11', email: 'eric.chi.king.mok@googlemail.com', :landline => '0191 2369458', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Richard', :last_name => 'Bradley', :mobile => '07889 059852', :membership_number => 'S902', :membership_type_id => '11', email: '', :landline => '0191 2520334', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Brian', :last_name => 'Martindale', :mobile => '07917 244594', :membership_number => 'S903', :membership_type_id => '11', email: 'bm@bmekm.plus.com', :landline => '0191 2964545', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Simon', :last_name => 'Ho', :mobile => '07971 238311', :membership_number => 'S905', :membership_type_id => '11', email: 'simon.ho@blueyonder.co.uk', :landline => '0191 2560412', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Steve', :last_name => 'Hodgson', :mobile => '07740 879584', :membership_number => 'S908', :membership_type_id => '11', email: 'Shodgson@post.com', :landline => '01670 513559', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Dave', :last_name => 'Tomson', :mobile => '07939 120076', :membership_number => 'S914', :membership_type_id => '11', email: 'd.p.c.tomson@ncl.ac.uk', :landline => '0191 2655636', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Lee', :last_name => 'Wratten', :mobile => '07974 443107', :membership_number => 'S915', :membership_type_id => '11', email: '', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Stuart', :last_name => 'Parkes', :mobile => '07875 516846', :membership_number => 'S916', :membership_type_id => '11', email: 'stuart.parkes@yahoo.com', :landline => '0191 6593136', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Ged', :last_name => 'O''Reilly', :mobile => '07531 541035', :membership_number => 'S917', :membership_type_id => '11', email: 'gedoreilly@googlemail.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Tony', :last_name => 'Garrity', :mobile => '07909 577792', :membership_number => 'S918', :membership_type_id => '11', email: 'tgarrity@btconnect.com', :landline => '0191 2520619', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Graeme', :last_name => 'Wallace', :mobile => '07790 818803', :membership_number => 'S921', :membership_type_id => '11', email: 'gkam.wallace@sky.com', :landline => '0191 2521679', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Steve', :last_name => 'Lines', :mobile => '', :membership_number => 'S923', :membership_type_id => '11', email: '', :landline => '0191 2901427', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Mark', :last_name => 'Armstrong ', :mobile => '07815 750965', :membership_number => 'S924', :membership_type_id => '11', email: 'markarmstrong@hotmail.com', :landline => '0191 2371587', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Alan', :last_name => 'Rakison', :mobile => '07762 176370', :membership_number => 'S926', :membership_type_id => '11', email: 'mail@alanrakison.co.uk', :landline => '0191 2363684', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Gordon', :last_name => 'Taylor', :mobile => '07909 530643', :membership_number => 'S930', :membership_type_id => '11', email: 'gtaylor@sky.com', :landline => '0191 274222', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Chris', :last_name => 'Reay', :mobile => '07976 374629', :membership_number => 'S931', :membership_type_id => '11', email: 'chris@christopherreay.co.uk', :landline => '0191 2801829', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Alan', :last_name => 'Thompson', :mobile => '', :membership_number => 'S932', :membership_type_id => '11', email: '', :landline => '0191 2527387', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Mark', :last_name => 'Midgley', :mobile => '07826 937485', :membership_number => 'S936', :membership_type_id => '11', email: 'midgas@hotmail.com', :landline => '0191 2923984', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Linda', :last_name => 'Bartram', :mobile => '07759 350661', :membership_number => 'S938', :membership_type_id => '11', email: '', :landline => '0191 2571653', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Lorna', :last_name => 'Cameron', :mobile => '07899 975566', :membership_number => 'S941', :membership_type_id => '11', email: 'lorna.cameron@blueyonder.co.uk', :landline => '0191 2530908', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Jon', :last_name => 'Brown', :mobile => '07816 518478', :membership_number => 'S942', :membership_type_id => '11', email: 'jonner1970@fsmail.net', :landline => '0191 2524581', :admin =>'false' ).first_or_create
Player.where(:first_name => 'John', :last_name => 'Wilson', :mobile => '07808 795955', :membership_number => 'S943', :membership_type_id => '11', email: '', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Steve', :last_name => 'Carrielies', :mobile => '', :membership_number => 'S945', :membership_type_id => '11', email: '', :landline => '0191 2570119', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Neil', :last_name => 'Mason', :mobile => '07779 076442', :membership_number => 'S946', :membership_type_id => '11', email: 'neilmason@madoscfish.com', :landline => '0191 2894178', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Michael', :last_name => 'Myers', :mobile => '07702 686439', :membership_number => 'S947', :membership_type_id => '11', email: 'mickjmyers@yahoo.co.uk', :landline => '0191 2911173', :admin =>'false' ).first_or_create
Player.where(:first_name => 'John', :last_name => 'Johnson', :mobile => '07721 643631', :membership_number => 'S948', :membership_type_id => '11', email: 'john.johnson53@btinternet.com', :landline => '01670 821981', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Brett', :last_name => 'Clark', :mobile => '07974 767019', :membership_number => 'S949', :membership_type_id => '11', email: 'brettene-marine.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'John', :last_name => 'Simpson', :mobile => '07885 794967', :membership_number => 'S952', :membership_type_id => '11', email: 'j.simpson@ncl.ac.uk', :landline => '0191 2402592', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Dave', :last_name => 'Sedgwick', :mobile => '07967 662684', :membership_number => 'S953', :membership_type_id => '11', email: 'dave@ion.co.uk', :landline => '0191 2855989', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Steven', :last_name => 'Elwick', :mobile => '07519 075091', :membership_number => 'S954', :membership_type_id => '11', email: 'elwicks17@googlemail.com', :landline => '0191 2500958', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Garry', :last_name => 'Sharples', :mobile => '07904 596122', :membership_number => 'S956', :membership_type_id => '11', email: 'garrysharples@hotmail.co.uk', :landline => '0191 2658667', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Chris', :last_name => 'Wall', :mobile => '07738 736958', :membership_number => 'S957', :membership_type_id => '11', email: 'chris.wall@tynemet.ac.uk', :landline => '0191 2582734', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Geoff', :last_name => 'Smithson', :mobile => '07795 546456', :membership_number => 'S958', :membership_type_id => '11', email: 'geoffsmithson@btinternet.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Mark', :last_name => 'Newlands', :mobile => '07504 715133', :membership_number => 'S959', :membership_type_id => '11', email: 'newlands9@blueyonder.co.uk', :landline => '0191 2802127', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Nik', :last_name => 'Lowery', :mobile => '07974 132068', :membership_number => 'S961', :membership_type_id => '11', email: 'nik.lowery@greeneking.co.uk', :landline => '0191 2528622', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Helen', :last_name => 'Dobinson', :mobile => '07861 885556', :membership_number => 'S962', :membership_type_id => '11', email: 'helendobinson25@gmail.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Kane', :last_name => 'Mather', :mobile => '', :membership_number => 'S965', :membership_type_id => '11', email: '', :landline => '0191 2096211', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Neil', :last_name => 'Pringle', :mobile => '07717 786855', :membership_number => 'S966', :membership_type_id => '11', email: 'neil.pringle@blueyonder.co.uk', :landline => '0191 2920000', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Ken', :last_name => 'Willis', :mobile => '07939 001225', :membership_number => 'S967', :membership_type_id => '11', email: '', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Paul', :last_name => 'Allen', :mobile => '', :membership_number => 'S968', :membership_type_id => '11', email: 'paooze8608@blueyonder.co.uk', :landline => '0191 2911381', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Alan', :last_name => 'Rycroft', :mobile => '07971 001384', :membership_number => 'S969', :membership_type_id => '11', email: 'artof.motorcycling@virgin.net', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Alan', :last_name => 'Richardson', :mobile => '07770 404745', :membership_number => 'S970', :membership_type_id => '11', email: 'alan.richardson@tiscali.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Mike', :last_name => 'De Vies', :mobile => '07969 875379', :membership_number => 'S972', :membership_type_id => '11', email: 'louis.devies@gmail.com', :landline => '0191 4556553', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Richard', :last_name => 'Williams', :mobile => '07590 927172', :membership_number => 'S979', :membership_type_id => '11', email: 'rw68@me.com', :landline => '0191 2584323', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Matthew', :last_name => 'Coe', :mobile => '07729 834044', :membership_number => 'S985', :membership_type_id => '11', email: 'coematthew@hotmail.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Fiona', :last_name => 'MacFarlane', :mobile => '07866 516351', :membership_number => 'S987', :membership_type_id => '11', email: 'fimacfarlane@hotmail.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Helen', :last_name => 'Watson', :mobile => '07739 967219', :membership_number => 'S989', :membership_type_id => '11', email: 'nellwatson@hotmail.com', :landline => '0191 2528672', :admin =>'false' ).first_or_create
Player.where(:first_name => 'David', :last_name => 'Gebhard', :mobile => '07768 637680', :membership_number => 'S990', :membership_type_id => '11', email: 'davidgebhard@hotmail.com', :landline => '0191 490 1736', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Dave', :last_name => 'Forrest', :mobile => '', :membership_number => 'S996', :membership_type_id => '11', email: '', :landline => '0191 2571546', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Grace', :last_name => 'Metcalfe', :mobile => '07800 944149', :membership_number => 'T090', :membership_type_id => '12', email: 'yahyahmate@yahoo.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Georgie', :last_name => 'Hind', :mobile => '07790 293677', :membership_number => 'T091', :membership_type_id => '12', email: '', :landline => '0191 2512139', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Johnny', :last_name => 'Perez', :mobile => '07806 572999', :membership_number => 'T103', :membership_type_id => '12', email: 'johnny.perez@park-resorts.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'John', :last_name => 'Harfoot', :mobile => '07930 451676', :membership_number => 'T117', :membership_type_id => '12', email: '', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Paul', :last_name => 'Manning', :mobile => '07502 221080', :membership_number => 'T120', :membership_type_id => '12', email: 'manning.paul@btinternet.com', :landline => '0191 2709027', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Thomas', :last_name => 'Dunwoodie', :mobile => '07530 105787', :membership_number => 'T121', :membership_type_id => '12', email: 'toni-burgo@hotmail.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Alhamza', :last_name => 'Alkhatib', :mobile => '07545 776539', :membership_number => 'T122', :membership_type_id => '12', email: 'a.alkhatib@me.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Damian', :last_name => 'Holliman', :mobile => '07427 667332', :membership_number => 'T125', :membership_type_id => '12', email: 'damian.holliman@gmail.com', :landline => '0191 2336161', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Tony', :last_name => 'Webster', :mobile => '07557 418998', :membership_number => 'T126', :membership_type_id => '12', email: 'tonywebsterpms@aol.com', :landline => '0191 4476982', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Mike', :last_name => 'Parr', :mobile => '07966 676450', :membership_number => 'T127', :membership_type_id => '12', email: 'mikeparr@gmail.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Allison', :last_name => 'McCall', :mobile => '07983 563933', :membership_number => 'T128', :membership_type_id => '12', email: 'allimac44@me.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Liam', :last_name => 'Howes', :mobile => '07519 659244', :membership_number => 'T129', :membership_type_id => '12', email: 'liam_howes@yahoo.com', :landline => '0191 2345846', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Tom', :last_name => 'Middleton', :mobile => '07810 556345', :membership_number => 'T130', :membership_type_id => '12', email: 'tom.minnleton@btinternet.com', :landline => '0191 2702137', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Kathryn', :last_name => 'Desborough', :mobile => '07817 326429', :membership_number => 'T131', :membership_type_id => '12', email: 'kathryn.desborough@gmail.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Kris', :last_name => 'Furness', :mobile => '07968 534127', :membership_number => 'T132', :membership_type_id => '12', email: 'krisfurness@gmail.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Michael', :last_name => 'Phillips', :mobile => '07538 658344', :membership_number => 'T133', :membership_type_id => '12', email: 'mike@fat-hippo.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Alex', :last_name => 'Bela', :mobile => '07889 029043', :membership_number => 'T134', :membership_type_id => '12', email: 'alexabela@hotmail.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'William', :last_name => 'Benson', :mobile => '07896 928189', :membership_number => 'T135', :membership_type_id => '12', email: 'beson.will@gmail.com', :landline => '0191 2814603', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Mark', :last_name => 'Peters', :mobile => '07885 982116', :membership_number => 'T136', :membership_type_id => '12', email: 'mark.peters@gmail.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Bill', :last_name => 'Taylor', :mobile => '07790 156705', :membership_number => 'T137', :membership_type_id => '12', email: 'billy56taylor@yahoo.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Abiodun', :last_name => 'Bamidele', :mobile => '07888 755809', :membership_number => 'T139', :membership_type_id => '12', email: 'abiodun.b@gmail.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Michael', :last_name => 'Chapman', :mobile => '07715 575253', :membership_number => 'T140', :membership_type_id => '12', email: 'm.a.chapman@hotmail.co.uk', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Adam', :last_name => 'Smith', :mobile => '07504 824817', :membership_number => 'T141', :membership_type_id => '12', email: '', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Philip', :last_name => 'Watt', :mobile => '', :membership_number => 'T142', :membership_type_id => '12', email: 'finefitbathrooms@googlemail.com', :landline => '0191 2895911', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Tim', :last_name => 'Watt', :mobile => '07974 808525', :membership_number => 'T143', :membership_type_id => '12', email: 'tpwatt@sky.com', :landline => '0191 6899278', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Martin', :last_name => 'Minnock', :mobile => '07808 826931', :membership_number => 'T144', :membership_type_id => '12', email: 'martinminnock@gmail.com', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Liz', :last_name => 'Lingard', :mobile => '07970 352678', :membership_number => 'T145', :membership_type_id => '12', email: 'lizlinguard@btinternet.com', :landline => '0191 2853406', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Darran', :last_name => 'Blackshaw', :mobile => '07739 785186', :membership_number => 'T146', :membership_type_id => '12', email: 'darranblackshaw@hotmail.co.uk', :landline => '0191 2894885', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Tracey', :last_name => 'King', :mobile => '', :membership_number => 'T147', :membership_type_id => '12', email: '', :landline => '0191 2894885', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Lee', :last_name => 'Murphy', :mobile => '07521 796567', :membership_number => 'T148', :membership_type_id => '12', email: 'leemurphy11@hotmail.co.uk', :landline => '0191 2950542', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Norman', :last_name => 'Robinson', :mobile => '07516 327388', :membership_number => 'T149', :membership_type_id => '12', email: '', :landline => '', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Joshua', :last_name => 'Todd', :mobile => '07427 158300', :membership_number => 'T150', :membership_type_id => '12', email: 'joshua_todd@hotmail.co.uk', :landline => '0191 2585833', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Alex', :last_name => 'O''Brien', :mobile => '07522 524642', :membership_number => 'T151', :membership_type_id => '12', email: 'alex@lolajeans.co.uk', :landline => '0191 2577601', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Christopher', :last_name => 'Bell', :mobile => '07779 985613', :membership_number => 'T152', :membership_type_id => '12', email: 'christopher.bell677@gmail.com', :landline => '0191 2896650', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Andrew', :last_name => 'Bell', :mobile => '07527 054901', :membership_number => 'T153', :membership_type_id => '12', email: 'abne15064@blueyonder.co.uk', :landline => '0191 2896650', :admin =>'false' ).first_or_create
Player.where(:first_name => 'Martin', :last_name => 'Wiliamson', :mobile => '07794 965674', :membership_number => 'T154', :membership_type_id => '12', email: 'martinwilliamson@me.com', :landline => '', :admin =>'false').first_or_create