namespace :archive do
  desc "Archive all inactive guest accounts"  
  task :guests => :environment do
    puts "guests:"
    Player.where('membership_type_id = 15').find_each do |guest|
    # player = Player.find(:first, :order => 'RANDOM()')
      if guest.future_bookings.count == 0 && guest.future_vs_bookings.count == 0
        puts "#{guest.full_name}"
        guest.archived = true
        guest.save
      end
    end
  end
  
  desc "Archived accounts"  
  task :list => :environment do
    puts "archived:"
    Player.where('archived = true').find_each do |player|
        puts "#{player.full_name}"
    end
  end
  
  desc "Remove non-renewed accounts"
  task :non_renewed => :environment do
    puts "non-renewed:"
    searchList.each do |full_name|

      members = Player.where("first_name || ' ' || last_name ILIKE ?", full_name)

      if members.count > 1
        puts "too many matches: #{full_name}"
      end

      member = members.first
      if member != nil
        puts "#{member.membership_number}"
      else
        puts "invalid member: #{full_name}"
      end
    end
  end
  
  desc "non-renewed accounts to remove"
  task :retrieve_accounts => :environment do
    puts ":retrieve_accounts:"
    removeList.each do |member_id|
      member = Player.where("membership_number = ?", member_id).first
      if member != nil
        if member.bookings_after(Date.today - 3.months).count == 0 && member.future_vs_bookings.count == 0 && member.archived == false
          puts "#{member.full_name}"
          member.archived = true
          member.save
        end
      end
    end
  end
  
   def searchList
    return ["Andrew Bell",
 "Josh Bell",
 "William Benson",
 "Cameron Berry",
 "Jospeh Black",
 "Guest Blackett",
 "Guest Blakey",
 "Christopher Blight",
 "Guest Bob",
 "Daniel Booth",
 "Louis Booth",
 "Chris Brock",
 "Stephen Bruce",
 "Ryder Buchanan",
 "Aimee Elen Cadwallader",
 "Lee Campbell",
 "Steve Carney",
 "Alex Carr",
 "Alison Carr",
 "Danny Carr",
 "Matthew Carr",
 "Ben Chambers",
 "Chris Chapman",
 "Michael Chapman",
 "Allan Charlton",
 "Brett Clark",
 "Matthew Coe",
 "Paul Collins",
 "Guest Collinson",
 "Rory Colthart",
 "Michael Constable",
 "Steven Cooper",
 "Ron Crow",
 "Nick Cubley",
 "Jordan Cummings",
 "Guest Curran",
 "Niamh Dallat",
 "Ryan Dallat",
 "Becky Day",
 "Phil Deighton",
 "Guest Delgaty",
 "Michael Denton",
 "Kathryn Desborough",
 "Mike DeVies",
 "Maya Dixon",
 "Helen Dobinson",
 "Zara Dodd",
 "Elizabeth Dodds",
 "Ian Dodson",
 "Liam Duncan-Kahn",
 "Georgina Dunkley",
 "Guest Dunn",
 "Steven Elqick",
 "Meddy Eniona",
 "Nicole Esposito",
 "Ben Evans",
 "Sam Ewing",
 "David Favour",
 "Guest Fenwick",
 "Ian Ferguson",
 "Liam Ferguson",
 "Heston Floyd",
 "Samuel Floyd",
 "Cait Foley",
 "Jack Foster",
 "Kris Furness",
 "Glover Gamero",
 "David Garr",
 "Tony Garrity",
 "Josh Gebhard",
 "George Gill",
 "Laurie Giraldo",
 "Ross Gladwin",
 "Daniel Goodinson",
 "Cameron Gunn",
 "Cameron Gunn",
 "Robin Gunn",
 "Tony Guy",
 "Duncan Hamilton",
 "Brian Hardy",
 "Mabel Harrington",
 "George Harrison",
 "David Hearl",
 "Jack Hearn",
 "Kevin Henderson",
 "Georgie Hind",
 "Dean Hogarty",
 "Kevin Hogarty",
 "Helena Holford",
 "Max Holford",
 "Michael Holford",
 "Minnie Holford",
 "Damian Holliman",
 "Martyn Hope",
 "David Hopwood",
 "Kerry Hopwood",
 "Graham Hornby",
 "Sarah Hornby",
 "David Houston",
 "Liam Howes",
 "David Hunter",
 "Jospeh Hunter",
 "Nick Hunter",
 "Jamil Hussain",
 "Cameron Ilderton",
 "Eddie Ilderton",
 "Steven Jacobs",
 "Guest James",
 "Ryan Jefferson",
 "John Johnson",
 "Aled Jones",
 "Biju Joseph",
 "Libby Kahn",
 "Ipsen Kathryn",
 "Iain Keir",
 "Martin Kellaway",
 "Simon Kellet",
 "Steven King",
 "Guest Laffey",
 "Adrian Laffey",
 "Dean Laidler",
 "Christopher Law",
 "Claire Leadstone",
 "David Leadstone",
 "Guest Lee",
 "Liz Lingard",
 "Daniel Love",
 "Adam Manley",
 "Alex Manning",
 "Paul Manning",
 "Aleksis Martindale",
 "Gill Mason",
 "Graeme Mason",
 "Neil Mason",
 "Fiona McCallion",
 "Angela McGhee",
 "Andrew McIntosh",
 "Kate McIntosh",
 "Lucy McIntosh",
 "Chris Mclane",
 "Ross Mclane",
 "Jack McLeod",
 "Peter McLeod",
 "James McMichael",
 "Andrew McVicar",
 "Chris Meade",
 "Rachael Meade",
 "Grace Meehan",
 "Grace Metcalfe",
 "Robert Miller",
 "Lisa Millington",
 "Martin Minnock",
 "Faye Mitcheson",
 "David Moir",
 "Thomas Moore",
 "Lee Murphy",
 "Michael Myers",
 "Doug Nicholson",
 "Alex O Brien",
 "Adam Oliver",
 "Wayne Oliver",
 "Susan O'Neil",
 "Ged O Reilly",
 "Charlotte Osborn",
 "Nick Paddock",
 "Stuart Parkes",
 "Mike Parr",
 "Deborah Percy",
 "Johhny Perez",
 "Daniel Perrelli",
 "Mark Peters",
 "Michael Phillips",
 "Thomas Porter",
 "Guest Power",
 "Guest Power",
 "Matthew Pringle",
 "Andrew Purdy",
 "Monica Readman",
 "Chris Reah",
 "Oscar Reay",
 "Dave Rhodes",
 "Jane Ridley",
 "Lee Robinson",
 "Norman Robinson",
 "Yvonne Routledge",
 "Claire Sampson",
 "Maxine Santana",
 "Guest Savage",
 "Catherine Scott",
 "Jo Scott",
 "Jon Scott",
 "Josef Scott",
 "Dave Sedwick",
 "Carl Siddall",
 "Callum Simpson",
 "Jonny Simpson",
 "Alexandra Slone",
 "Adam Smith",
 "Alex Smith",
 "Dean Smith",
 "Ian Smith",
 "Richard Steele",
 "Dennis Stewart",
 "Matthew Stewart",
 "Daryl Stoker",
 "Ben Storey",
 "John Swanston",
 "Catherine Tate",
 "Bill Taylor",
 "Stan Taylor",
 "Steve Taylor",
 "Chris Thompson",
 "Matthew Thompson",
 "Richard Thompson",
 "Alison Todd",
 "Joshua Todd",
 "Sam Todd",
 "Dave Tomson",
 "Ethan Veitch",
 "Graeme Wallace",
 "Katie Waller",
 "Philip Warwick",
 "Helen Watson",
 "Mark Watson",
 "Philip Watt",
 "Tim Watt",
 "Martin Wiliamson",
 "Richard Williams",
 "Judith Wills",
 "Matthew Wills",
 "Daniel Wilson",
 "Nathon Wong",
 "Thomas Wong",
 "Keith Worrall",
 "Tegan Younger"]
end
  
  def removeList
    return ["S153",
      "IS046",
      "T135",
      "J411",
      "T502",
      "F902",
      "F903",
      "S174",
      "S783",
      "IS024",
      "IS045",
      "S344",
      "S025",
      "J002",
      "IS102",
      "T993",
      "J003",
      "S874",
      "T140",
      "S093",
      "S949",
      "S985",
      "T162",
      "T155",
      "S411",
      "T978",
      "S532",
      "J454",
      "S454",
      "S256",
      "IS047",
      "T131",
      "T972",
      "J415",
      "S962",
      "R141",
      "C049",
      "T163",
      "J435",
      "T980",
      "guest_1105",
      "J470",
      "T161",
      "S287",
      "guest_1088",
      "T983",
      "IS048",
      "S265",
      "R064",
      "T132",
      "S253",
      "S918",
      "S107",
      "S869",
      "T504",
      "T996",
      "R068",
      "J426",
      "S197",
      "S005",
      "T981",
      "S083",
      "J406",
      "S289",
      "J476",
      "J354",
      "T170",
      "T091",
      "R055",
      "R058",
      "F802",
      "F803",
      "F804",
      "T125",
      "Is054",
      "Co063",
      "Co064",
      "LM019",
      "T129",
      "S101",
      "T975",
      "J463",
      "T484",
      "S424",
      "guest_837",
      "J428",
      "S948",
      "R142",
      "T160",
      "T503",
      "S782",
      "S124",
      "T985",
      "R067",
      "T987",
      "J431",
      "G431",
      "J216",
      "T156",
      "J462",
      "T120",
      "IS050",
      "S462",
      "R046",
      "R053",
      "s406",
      "J456",
      "J455",
      "R975",
      "J423",
      "J481",
      "S346",
      "R065",
      "T499",
      "S249",
      "S250",
      "S157",
      "T090",
      "IS052",
      "F104",
      "J440",
      "S876",
      "J458",
      "T148",
      "S947",
      "T974",
      "T496",
      "S379",
      "S255",
      "S916",
      "T127",
      "Co062",
      "T986",
      "T136",
      "J457",
      "S251",
      "232",
      "S173",
      "J404",
      "S984",
      "F901",
      "T149",
      "Co052",
      "T494",
      "T979",
      "J464",
      "Co060",
      "Co059",
      "J203",
      "S152",
      "J418",
      "S781",
      "IS053",
      "T141",
      "J477",
      "T994",
      "S463",
      "S608",
      "J478",
      "IS155",
      "S259",
      "R272",
      "R066",
      "C214",
      "F402",
      "T150",
      "IS049",
      "S914",
      "J473",
      "S921",
      "J396",
      "S897",
      "S254",
      "T142",
      "T143",
      "S979",
      "F702",
      "F704",
      "S359",
      "J417",
      "J422"]
  end
end