# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

MembershipType.create([
  { membership_type: 'country', court_cost: '6.00', membership_cost: '1000'},
  { membership_type: 'family', court_cost: '6.00', membership_cost: '1000'},
  { membership_type: 'junior', court_cost: '3.00', membership_cost: '1000'},
  { membership_type: 'couple', court_cost: '6.00', membership_cost: '1000'},
  { membership_type: 'gym', court_cost: '6.00', membership_cost: '1000'},
  { membership_type: 'student', court_cost: '3.00', membership_cost: '1000'},
  { membership_type: 'full', court_cost: '6.00', membership_cost: '1000'},
  { membership_type: 'life', court_cost: '6.00', membership_cost: '1000'},
  { membership_type: 'social', court_cost: '6.00', membership_cost: '1000'},
  { membership_type: 'restricted', court_cost: '6.00', membership_cost: '1000'},
  { membership_type: 'trial', court_cost: '6.00', membership_cost: '1000'},
  { membership_type: 'nonmember', court_cost: '12.00', membership_cost: '1000'},
  { membership_type: 'guest', court_cost: '7.00', membership_cost: '1000'},
  
])

Player.create([
{ first_name: 'Stuart', last_name: 'Varrall', telephone: '0191', membership_number: '100', membership_type_id: '3', admin: 'true'},
{ first_name: 'Chris', last_name: 'Thompson', telephone: '07834 616434', membership_number: 'C036', membership_type_id: '0', admin:'false'},
{ first_name: 'Mark', last_name: 'Williamson ', telephone: '07715 305225', membership_number: 'C042', membership_type_id: '0', admin:'false'},
{ first_name: 'Keith', last_name: 'Watson', telephone: '', membership_number: 'C043', membership_type_id: '0', admin:'false'},
{ first_name: 'Dennis', last_name: 'Cosgrove', telephone: '07540 721027', membership_number: 'C045', membership_type_id: '0', admin:'false'},
{ first_name: 'Nathan', last_name: 'Chidambaram', telephone: '7879084102', membership_number: 'C047', membership_type_id: '0', admin:'false'},
{ first_name: 'John', last_name: 'Smith', telephone: '', membership_number: 'C048', membership_type_id: '0', admin:'false'},
{ first_name: 'Elizabeth', last_name: 'Dodds', telephone: '07711 887778', membership_number: 'C049', membership_type_id: '0', admin:'false'},
{ first_name: 'Christopher', last_name: 'Appleby ', telephone: '7590692976', membership_number: 'C050', membership_type_id: '0', admin:'false'},
{ first_name: 'Thomas', last_name: 'Elves', telephone: '7885571731', membership_number: 'C051', membership_type_id: '0', admin:'false'},
{ first_name: 'Peter', last_name: 'Slaughter', telephone: '781620168', membership_number: 'C052', membership_type_id: '0', admin:'false'},
{ first_name: 'James', last_name: 'Millican', telephone: '7545202098', membership_number: 'C053', membership_type_id: '0', admin:'false'},
{ first_name: 'Sean', last_name: 'Took', telephone: '07950 287704', membership_number: 'C718', membership_type_id: '0', admin:'false'},
{ first_name: 'Henry', last_name: 'Armstrong', telephone: '07581 240261', membership_number: 'Co037', membership_type_id: '3', admin:'false'},
{ first_name: 'Barbara', last_name: 'Armstrong', telephone: '7803248399', membership_number: 'Co038', membership_type_id: '3', admin:'false'},
{ first_name: 'Dawn', last_name: 'Ward', telephone: '', membership_number: 'Co039', membership_type_id: '3', admin:'false'},
{ first_name: 'Glenn', last_name: 'Ward', telephone: '', membership_number: 'Co040', membership_type_id: '3', admin:'false'},
{ first_name: 'Sharron', last_name: 'Mather', telephone: '07962 184256', membership_number: 'Co041', membership_type_id: '3', admin:'false'},
{ first_name: 'George', last_name: 'Mather', telephone: '', membership_number: 'Co042', membership_type_id: '3', admin:'false'},
{ first_name: 'Alan', last_name: 'Wall', telephone: '07710 124412', membership_number: 'Co049', membership_type_id: '3', admin:'false'},
{ first_name: 'Janet', last_name: 'Wall', telephone: '07759 312270', membership_number: 'Co050', membership_type_id: '3', admin:'false'},
{ first_name: 'Richard', last_name: 'Routledge', telephone: '07778 792288', membership_number: 'Co051', membership_type_id: '3', admin:'false'},
{ first_name: 'Yvonne', last_name: 'Routledge', telephone: '07825 713113', membership_number: 'Co052', membership_type_id: '3', admin:'false'},
{ first_name: 'Ruth', last_name: 'Varrall', telephone: '7754295378', membership_number: 'Co054', membership_type_id: '3', admin:'false'},
{ first_name: 'Gill', last_name: 'Millington', telephone: '', membership_number: 'F005', membership_type_id: '1', admin:'false'},
{ first_name: 'Lisa', last_name: 'Millington', telephone: '', membership_number: 'F005', membership_type_id: '1', admin:'false'},
{ first_name: 'Paul', last_name: 'Millington', telephone: '', membership_number: 'F005', membership_type_id: '1', admin:'false'},
{ first_name: 'Sean', last_name: 'Millington', telephone: '', membership_number: 'F005', membership_type_id: '1', admin:'false'},
{ first_name: 'Daisy', last_name: 'Dobson', telephone: '', membership_number: 'F006', membership_type_id: '1', admin:'false'},
{ first_name: 'Nathan', last_name: 'Dobson', telephone: '7731753379', membership_number: 'F006', membership_type_id: '1', admin:'false'},
{ first_name: 'Nicky', last_name: 'Dobson', telephone: '07958 006606', membership_number: 'F006', membership_type_id: '1', admin:'false'},
{ first_name: 'Wayne', last_name: 'Dobson', telephone: '', membership_number: 'F006', membership_type_id: '1', admin:'false'},
{ first_name: 'Lucy', last_name: 'Beecroft', telephone: '', membership_number: 'F008', membership_type_id: '1', admin:'false'},
{ first_name: 'Paul', last_name: 'Beecroft', telephone: '07790 734560', membership_number: 'F008', membership_type_id: '1', admin:'false'},
{ first_name: 'Susan', last_name: 'Beecroft', telephone: '', membership_number: 'F008', membership_type_id: '1', admin:'false'},
{ first_name: 'Kevin', last_name: 'Wills', telephone: '07768 061358', membership_number: 'F009', membership_type_id: '1', admin:'false'},
{ first_name: 'Judith', last_name: 'Wills', telephone: '', membership_number: 'F009', membership_type_id: '1', admin:'false'},
{ first_name: 'Jamie', last_name: 'Wills', telephone: '', membership_number: 'F009', membership_type_id: '1', admin:'false'},
{ first_name: 'Matthew', last_name: 'Wills', telephone: '', membership_number: 'F009', membership_type_id: '1', admin:'false'},
{ first_name: 'Seamus', last_name: 'McCallion', telephone: '07775 933437', membership_number: 'F010', membership_type_id: '1', admin:'false'},
{ first_name: 'Lesley', last_name: 'McCallion', telephone: '7816220167', membership_number: 'F010', membership_type_id: '1', admin:'false'},
{ first_name: 'Orla', last_name: 'McCallion', telephone: '', membership_number: 'F010', membership_type_id: '1', admin:'false'},
{ first_name: 'Aidan', last_name: 'McCallion', telephone: '', membership_number: 'F010', membership_type_id: '1', admin:'false'},
{ first_name: 'Dave', last_name: 'Todd', telephone: '7842820706', membership_number: 'F011', membership_type_id: '1', admin:'false'},
{ first_name: 'Alison', last_name: 'Todd', telephone: '7563691204', membership_number: 'F011', membership_type_id: '1', admin:'false'},
{ first_name: 'Jamie', last_name: 'Todd', telephone: '07547 856123', membership_number: 'F011', membership_type_id: '1', admin:'false'},
{ first_name: 'Darren', last_name: 'Lockwood', telephone: '7935122582', membership_number: 'F012', membership_type_id: '1', admin:'false'},
{ first_name: 'Beverley', last_name: 'Lockwood', telephone: '7935122582', membership_number: 'F012', membership_type_id: '1', admin:'false'},
{ first_name: 'Charlie', last_name: 'Lockwood', telephone: '7935122582', membership_number: 'F012', membership_type_id: '1', admin:'false'},
{ first_name: 'Lennox', last_name: 'Lockwood', telephone: '7935122582', membership_number: 'F012', membership_type_id: '1', admin:'false'},
{ first_name: 'David', last_name: 'Snedden', telephone: '7515571328', membership_number: 'Gym05', membership_type_id: '4', admin:'false'},
{ first_name: 'Denise', last_name: 'Bolt', telephone: '07811 978443', membership_number: 'Gym10', membership_type_id: '4', admin:'false'},
{ first_name: 'Sharon', last_name: 'Allen', telephone: '07969 204402', membership_number: 'Gym11', membership_type_id: '4', admin:'false'},
{ first_name: 'Andrew', last_name: 'Watson', telephone: '7858318458', membership_number: 'Gym12', membership_type_id: '4', admin:'false'},
{ first_name: 'Ross', last_name: 'Mazzucchi', telephone: '', membership_number: 'IS019', membership_type_id: '5', admin:'false'},
{ first_name: 'Hannah', last_name: 'Cliff', telephone: '', membership_number: 'IS020', membership_type_id: '5', admin:'false'},
{ first_name: 'Sam', last_name: 'Ward', telephone: '', membership_number: 'IS021', membership_type_id: '5', admin:'false'},
{ first_name: 'Michelle', last_name: 'Proctor', telephone: '7903030753', membership_number: 'IS022', membership_type_id: '5', admin:'false'},
{ first_name: 'Lee', last_name: 'Robinson', telephone: '7593577853', membership_number: 'IS025', membership_type_id: '5', admin:'false'},
{ first_name: 'David', last_name: 'Mazzucchi', telephone: '', membership_number: 'IS034', membership_type_id: '5', admin:'false'},
{ first_name: 'Robert', last_name: 'Bolt', telephone: '07857 129471', membership_number: 'IS039', membership_type_id: '5', admin:'false'},
{ first_name: 'William', last_name: 'Berry', telephone: '', membership_number: 'IS041', membership_type_id: '5', admin:'false'},
{ first_name: 'Daniel', last_name: 'Hockborn', telephone: '07814 031183', membership_number: 'IS042', membership_type_id: '5', admin:'false'},
{ first_name: 'Hannah', last_name: 'Crichton', telephone: '7789262391', membership_number: 'IS045', membership_type_id: '5', admin:'false'},
{ first_name: 'Sophie', last_name: 'Watson', telephone: '7540758436', membership_number: 'IS046', membership_type_id: '5', admin:'false'},
{ first_name: 'James', last_name: 'Field', telephone: '7736045098', membership_number: 'IS047', membership_type_id: '5', admin:'false'},
{ first_name: 'Liam', last_name: 'Ferguson', telephone: '7867991192', membership_number: 'IS048', membership_type_id: '5', admin:'false'},
{ first_name: 'Lauren', last_name: 'Gray', telephone: '7817418659', membership_number: 'IS049', membership_type_id: '5', admin:'false'},
{ first_name: 'Alex', last_name: 'Carr', telephone: '', membership_number: 'J002', membership_type_id: '2', admin:'false'},
{ first_name: 'Matthew', last_name: 'Carr', telephone: '', membership_number: 'J003', membership_type_id: '2', admin:'false'},
{ first_name: 'Tom', last_name: 'Walsh', telephone: '', membership_number: 'J007', membership_type_id: '2', admin:'false'},
{ first_name: 'Andrew', last_name: 'Walsh', telephone: '', membership_number: 'J008', membership_type_id: '2', admin:'false'},
{ first_name: 'Matthew', last_name: 'Walsh', telephone: '', membership_number: 'J009', membership_type_id: '2', admin:'false'},
{ first_name: 'Josh', last_name: 'Gebhard', telephone: '07827 322337', membership_number: 'J107', membership_type_id: '6', admin:'false'},
{ first_name: 'Molly', last_name: 'O''Shannon', telephone: '', membership_number: 'J188', membership_type_id: '2', admin:'false'},
{ first_name: 'Adam', last_name: 'Robertson', telephone: '', membership_number: 'J193', membership_type_id: '2', admin:'false'},
{ first_name: 'Josef', last_name: 'Scott', telephone: '07772 147570', membership_number: 'J203', membership_type_id: '2', admin:'false'},
{ first_name: 'Daniel', last_name: 'Love', telephone: '', membership_number: 'J216', membership_type_id: '2', admin:'false'},
{ first_name: 'Nicholas', last_name: 'McIntyre', telephone: '', membership_number: 'J241', membership_type_id: '2', admin:'false'},
{ first_name: 'Jack', last_name: 'Hearn', telephone: '', membership_number: 'J354', membership_type_id: '2', admin:'false'},
{ first_name: 'James', last_name: 'Waller', telephone: '', membership_number: 'J395', membership_type_id: '2', admin:'false'},
{ first_name: 'Katie', last_name: 'Waller', telephone: '', membership_number: 'J396', membership_type_id: '2', admin:'false'},
{ first_name: 'Aleksis', last_name: 'Martindale', telephone: '07748 675279', membership_number: 'J403', membership_type_id: '2', admin:'false'},
{ first_name: 'Katrina', last_name: 'Martindale', telephone: '17891 060615', membership_number: 'J404', membership_type_id: '2', admin:'false'},
{ first_name: 'Samantha', last_name: 'Checkley', telephone: '', membership_number: 'J405', membership_type_id: '2', admin:'false'},
{ first_name: 'James', last_name: 'Armstrong', telephone: '07815 750965', membership_number: 'J408', membership_type_id: '2', admin:'false'},
{ first_name: 'Cameron', last_name: 'Berry', telephone: '', membership_number: 'J411', membership_type_id: '2', admin:'false'},
{ first_name: 'Katy', last_name: 'Albone', telephone: '', membership_number: 'J413', membership_type_id: '2', admin:'false'},
{ first_name: 'Emma Louise', last_name: 'Bates', telephone: '7957023097', membership_number: 'J414', membership_type_id: '2', admin:'false'},
{ first_name: 'Maya', last_name: 'Dixon', telephone: '7891058884', membership_number: 'J415', membership_type_id: '2', admin:'false'},
{ first_name: 'Nathan', last_name: 'Wong', telephone: '', membership_number: 'J416', membership_type_id: '2', admin:'false'},
{ first_name: 'Thomas', last_name: 'Wong', telephone: '', membership_number: 'J417', membership_type_id: '2', admin:'false'},
{ first_name: 'Callum', last_name: 'Simpson', telephone: '', membership_number: 'J418', membership_type_id: '2', admin:'false'},
{ first_name: 'Steven', last_name: 'Allen', telephone: '', membership_number: 'J420', membership_type_id: '2', admin:'false'},
{ first_name: 'Ross', last_name: 'McLane', telephone: '', membership_number: 'J423', membership_type_id: '2', admin:'false'},
{ first_name: 'Cameron', last_name: 'Gunn', telephone: '', membership_number: 'J426', membership_type_id: '2', admin:'false'},
{ first_name: 'Billy', last_name: 'Bolt', telephone: '07734 135060', membership_number: 'J439', membership_type_id: '2', admin:'false'},
{ first_name: 'Mitchell', last_name: 'Bolt', telephone: '7969187077', membership_number: 'J440', membership_type_id: '2', admin:'false'},
{ first_name: 'Laura', last_name: 'Neill', telephone: '7962428436', membership_number: 'J441', membership_type_id: '2', admin:'false'},
{ first_name: 'Daniel', last_name: 'Neill', telephone: '7962428436', membership_number: 'J442', membership_type_id: '2', admin:'false'},
{ first_name: 'Verity', last_name: 'Wright', telephone: '7790122390', membership_number: 'J443', membership_type_id: '2', admin:'false'},
{ first_name: 'Chris', last_name: 'Allen', telephone: '7802388729', membership_number: 'J444', membership_type_id: '2', admin:'false'},
{ first_name: 'Thomas', last_name: 'Skelton', telephone: '7825417294', membership_number: 'J445', membership_type_id: '2', admin:'false'},
{ first_name: 'Emily', last_name: 'King', telephone: '7501133624', membership_number: 'J446', membership_type_id: '2', admin:'false'},
{ first_name: 'Brooke', last_name: 'Bolt', telephone: '', membership_number: 'J447', membership_type_id: '2', admin:'false'},
{ first_name: 'David', last_name: 'Hearl', telephone: '7763029591', membership_number: 'J448', membership_type_id: '2', admin:'false'},
{ first_name: 'Amy', last_name: 'Love', telephone: '', membership_number: 'J449', membership_type_id: '2', admin:'false'},
{ first_name: 'Charlie', last_name: 'Took', telephone: '', membership_number: 'J450', membership_type_id: '2', admin:'false'},
{ first_name: 'Ellie', last_name: 'Brown', telephone: '', membership_number: 'J451', membership_type_id: '2', admin:'false'},
{ first_name: 'Ben', last_name: 'Evans', telephone: '7505626448', membership_number: 'J452', membership_type_id: '2', admin:'false'},
{ first_name: 'Sam', last_name: 'Evans', telephone: '7505626448', membership_number: 'J453', membership_type_id: '2', admin:'false'},
{ first_name: 'Niamh', last_name: 'Dallat', telephone: '', membership_number: 'J454', membership_type_id: '2', admin:'false'},
{ first_name: 'Tom', last_name: 'Hogarty', telephone: '', membership_number: 'J455', membership_type_id: '2', admin:'false'},
{ first_name: 'George', last_name: 'Hogarty', telephone: '', membership_number: 'J456', membership_type_id: '2', admin:'false'},
{ first_name: 'Lois', last_name: 'Bathgate', telephone: '', membership_number: 'J457', membership_type_id: '2', admin:'false'},
{ first_name: 'Steven', last_name: 'Bathgate', telephone: '', membership_number: 'J458', membership_type_id: '2', admin:'false'},
{ first_name: 'Rosa', last_name: 'Hall', telephone: '', membership_number: 'J459', membership_type_id: '2', admin:'false'},
{ first_name: 'Ivon', last_name: 'Holland', telephone: '', membership_number: 'J460', membership_type_id: '2', admin:'false'},
{ first_name: 'Steve', last_name: 'Cubbins', telephone: '07949 086158', membership_number: 'LM007', membership_type_id: '7', admin:'false'},
{ first_name: 'Cy', last_name: 'Dobson', telephone: '', membership_number: 'LM008', membership_type_id: '7', admin:'false'},
{ first_name: 'Alan', last_name: 'Douglas', telephone: '', membership_number: 'LM009', membership_type_id: '7', admin:'false'},
{ first_name: 'A', last_name: 'Gilberg', telephone: '', membership_number: 'LM010', membership_type_id: '7', admin:'false'},
{ first_name: 'A', last_name: 'Gofton', telephone: '', membership_number: 'LM012', membership_type_id: '7', admin:'false'},
{ first_name: 'Peter', last_name: 'Grant', telephone: '', membership_number: 'LM013', membership_type_id: '7', admin:'false'},
{ first_name: 'T', last_name: 'Hart', telephone: '', membership_number: 'LM016', membership_type_id: '7', admin:'false'},
{ first_name: 'N', last_name: 'Hewison', telephone: '', membership_number: 'LM018', membership_type_id: '7', admin:'false'},
{ first_name: 'David', last_name: 'Houston', telephone: '', membership_number: 'LM019', membership_type_id: '7', admin:'false'},
{ first_name: 'Francis', last_name: 'Kidd', telephone: '', membership_number: 'LM020', membership_type_id: '7', admin:'false'},
{ first_name: 'Steve', last_name: 'Laws', telephone: '', membership_number: 'LM022', membership_type_id: '7', admin:'false'},
{ first_name: 'N', last_name: 'Mathieson', telephone: '', membership_number: 'LM023', membership_type_id: '7', admin:'false'},
{ first_name: 'L', last_name: 'Myers', telephone: '', membership_number: 'LM024', membership_type_id: '7', admin:'false'},
{ first_name: 'Alan', last_name: 'McWhinnie', telephone: '', membership_number: 'LM025', membership_type_id: '7', admin:'false'},
{ first_name: 'L', last_name: 'Paterson', telephone: '', membership_number: 'LM026', membership_type_id: '7', admin:'false'},
{ first_name: 'G', last_name: 'Taylor', telephone: '', membership_number: 'LM028', membership_type_id: '7', admin:'false'},
{ first_name: 'C', last_name: 'Thompson', telephone: '', membership_number: 'LM029', membership_type_id: '7', admin:'false'},
{ first_name: 'W', last_name: 'Thompson', telephone: '', membership_number: 'LM030', membership_type_id: '7', admin:'false'},
{ first_name: 'D', last_name: 'Waters', telephone: '', membership_number: 'LM034', membership_type_id: '7', admin:'false'},
{ first_name: 'Tom', last_name: 'Waters', telephone: '', membership_number: 'LM035', membership_type_id: '7', admin:'false'},
{ first_name: 'J', last_name: 'White', telephone: '', membership_number: 'LM036', membership_type_id: '7', admin:'false'},
{ first_name: 'J', last_name: 'Young', telephone: '', membership_number: 'LM037', membership_type_id: '7', admin:'false'},
{ first_name: 'Garry', last_name: 'Burton', telephone: '', membership_number: 'LM038', membership_type_id: '7', admin:'false'},
{ first_name: 'Alan', last_name: 'Johnsen', telephone: '07505 092248', membership_number: 'LM039', membership_type_id: '7', admin:'false'},
{ first_name: 'Steve', last_name: 'Bertenshaw', telephone: '', membership_number: 'NP016', membership_type_id: '8', admin:'false'},
{ first_name: 'Paul', last_name: 'Dunn', telephone: '07831 382354', membership_number: 'NP021', membership_type_id: '8', admin:'false'},
{ first_name: 'Paul', last_name: 'Tebble', telephone: '', membership_number: 'NP027', membership_type_id: '8', admin:'false'},
{ first_name: 'Ian', last_name: 'Robertson', telephone: '07871 163369', membership_number: 'NP032', membership_type_id: '8', admin:'false'},
{ first_name: 'Stu', last_name: 'Ellis', telephone: '', membership_number: 'NP036', membership_type_id: '8', admin:'false'},
{ first_name: 'Peter', last_name: 'Forster', telephone: '', membership_number: 'NP044', membership_type_id: '8', admin:'false'},
{ first_name: 'Trevor', last_name: 'Wilkinson', telephone: '7904948912', membership_number: 'NP045', membership_type_id: '8', admin:'false'},
{ first_name: 'Milton', last_name: 'Stonebanks', telephone: '07814 087457', membership_number: 'NP050', membership_type_id: '8', admin:'false'},
{ first_name: 'Richard', last_name: 'Scott', telephone: '', membership_number: 'NP063', membership_type_id: '8', admin:'false'},
{ first_name: 'Monica', last_name: 'Readman', telephone: '7596984433', membership_number: 'NP064', membership_type_id: '8', admin:'false'},
{ first_name: 'Jenny', last_name: 'Ellis', telephone: '', membership_number: 'NP102', membership_type_id: '8', admin:'false'},
{ first_name: 'David', last_name: 'Barnes', telephone: '', membership_number: 'NP151', membership_type_id: '8', admin:'false'},
{ first_name: 'Robert', last_name: 'Davis', telephone: '', membership_number: 'NP174', membership_type_id: '8', admin:'false'},
{ first_name: 'Lilian', last_name: 'Davis', telephone: '', membership_number: 'NP175', membership_type_id: '8', admin:'false'},
{ first_name: 'Andrew', last_name: 'Ferguson', telephone: '7753434880', membership_number: 'NP176', membership_type_id: '8', admin:'false'},
{ first_name: 'Paul', last_name: 'Bolger', telephone: '', membership_number: 'NP178', membership_type_id: '8', admin:'false'},
{ first_name: 'Alan', last_name: 'Brown', telephone: '', membership_number: 'NP181', membership_type_id: '8', admin:'false'},
{ first_name: 'Arthur', last_name: 'Daniels', telephone: '', membership_number: 'NP188', membership_type_id: '8', admin:'false'},
{ first_name: 'Arne', last_name: 'Pedersen', telephone: '', membership_number: 'NP196', membership_type_id: '8', admin:'false'},
{ first_name: 'Pav', last_name: 'Bolger', telephone: '', membership_number: 'NP222', membership_type_id: '8', admin:'false'},
{ first_name: 'Ken', last_name: 'Brown', telephone: '', membership_number: 'NP224', membership_type_id: '8', admin:'false'},
{ first_name: 'Tim', last_name: 'Shield', telephone: '07748 268486', membership_number: 'NP233', membership_type_id: '8', admin:'false'},
{ first_name: 'Alan', last_name: 'Brookes', telephone: '', membership_number: 'NP245', membership_type_id: '8', admin:'false'},
{ first_name: 'Pat', last_name: 'Stanley', telephone: '07530 844163', membership_number: 'NP246', membership_type_id: '8', admin:'false'},
{ first_name: 'Iain', last_name: 'Simpson', telephone: '', membership_number: 'NP249', membership_type_id: '8', admin:'false'},
{ first_name: 'Dave', last_name: 'Smith', telephone: '', membership_number: 'NP251', membership_type_id: '8', admin:'false'},
{ first_name: 'William', last_name: 'Mankin', telephone: '', membership_number: 'NP261', membership_type_id: '8', admin:'false'},
{ first_name: 'Derek', last_name: 'Callaghan', telephone: '07866 255289', membership_number: 'NP266', membership_type_id: '8', admin:'false'},
{ first_name: 'Lee-Anne', last_name: 'Warwick', telephone: '07815 807156', membership_number: 'NP269', membership_type_id: '8', admin:'false'},
{ first_name: 'John', last_name: 'Laidler', telephone: '', membership_number: 'NP270', membership_type_id: '8', admin:'false'},
{ first_name: 'John', last_name: 'Guthrie', telephone: '', membership_number: 'NP274', membership_type_id: '8', admin:'false'},
{ first_name: 'William', last_name: 'Tindle', telephone: '', membership_number: 'NP275', membership_type_id: '8', admin:'false'},
{ first_name: 'Lesley', last_name: 'Barnett', telephone: '', membership_number: 'NP276', membership_type_id: '8', admin:'false'},
{ first_name: 'Beth', last_name: 'Brown', telephone: '7804799449', membership_number: 'NP277', membership_type_id: '8', admin:'false'},
{ first_name: 'Linda', last_name: 'Smith', telephone: '', membership_number: 'NP278', membership_type_id: '8', admin:'false'},
{ first_name: 'Irene', last_name: 'Wharton', telephone: '7904453772', membership_number: 'NP279', membership_type_id: '8', admin:'false'},
{ first_name: 'Bill', last_name: 'Brotherton', telephone: '', membership_number: 'NP280', membership_type_id: '8', admin:'false'},
{ first_name: 'Roger', last_name: 'Kyne', telephone: '7980902141', membership_number: 'NP281', membership_type_id: '8', admin:'false'},
{ first_name: 'Jim', last_name: 'Scott', telephone: '7790376151', membership_number: 'NP282', membership_type_id: '8', admin:'false'},
{ first_name: 'Maureen', last_name: 'Hancock', telephone: '', membership_number: 'NP283', membership_type_id: '8', admin:'false'},
{ first_name: 'Anthony', last_name: 'Golden', telephone: '7549256505', membership_number: 'NP284', membership_type_id: '8', admin:'false'},
{ first_name: 'Brian', last_name: 'Armstrong', telephone: '', membership_number: 'NP285', membership_type_id: '8', admin:'false'},
{ first_name: 'Elinor', last_name: 'Armstrong', telephone: '', membership_number: 'NP286', membership_type_id: '8', admin:'false'},
{ first_name: 'Mike', last_name: 'Walker', telephone: '7930347769', membership_number: 'NP287', membership_type_id: '8', admin:'false'},
{ first_name: 'Fiona', last_name: 'Simpson', telephone: '07790 703832', membership_number: 'NP288', membership_type_id: '8', admin:'false'},
{ first_name: 'Ailsa', last_name: 'Simpson', telephone: '', membership_number: 'NP289', membership_type_id: '8', admin:'false'},
{ first_name: 'Mark', last_name: 'Stephenson', telephone: '07525 269383', membership_number: 'NP290', membership_type_id: '8', admin:'false'},
{ first_name: 'Lisa', last_name: 'Jefferson', telephone: '07814 570077', membership_number: 'NP291', membership_type_id: '8', admin:'false'},
{ first_name: 'Keith', last_name: 'Appleby ', telephone: '07940 782187', membership_number: 'NP927', membership_type_id: '8', admin:'false'},
{ first_name: 'Marty', last_name: 'Hoult', telephone: '07768 376022', membership_number: 'NP960', membership_type_id: '8', admin:'false'},
{ first_name: 'Naomi', last_name: 'Walker', telephone: '7583056799', membership_number: 'R040', membership_type_id: '9', admin:'false'},
{ first_name: 'Rev Andrew', last_name: 'Beeston', telephone: '', membership_number: 'R041', membership_type_id: '9', admin:'false'},
{ first_name: 'Sylvia', last_name: 'Wilson', telephone: '', membership_number: 'R042', membership_type_id: '9', admin:'false'},
{ first_name: 'Ash', last_name: 'Fox', telephone: '07985 955777', membership_number: 'R049', membership_type_id: '9', admin:'false'},
{ first_name: 'David', last_name: 'Dolman', telephone: '', membership_number: 'R050', membership_type_id: '9', admin:'false'},
{ first_name: 'Paul', last_name: 'Athey', telephone: '07974 019635', membership_number: 'R051', membership_type_id: '9', admin:'false'},
{ first_name: 'Kevin', last_name: 'Bolt', telephone: '07722 243769', membership_number: 'R052', membership_type_id: '9', admin:'false'},
{ first_name: 'Chris', last_name: 'Bradley', telephone: '07961 007248', membership_number: 'R054', membership_type_id: '9', admin:'false'},
{ first_name: 'Jack', last_name: 'Foster', telephone: '', membership_number: 'R064', membership_type_id: '9', admin:'false'},
{ first_name: 'Stephanie', last_name: 'Gair', telephone: '07939 226188', membership_number: 'R071', membership_type_id: '9', admin:'false'},
{ first_name: 'Carol', last_name: 'Liddle', telephone: '', membership_number: 'R072', membership_type_id: '9', admin:'false'},
{ first_name: 'Miriam', last_name: 'Evans', telephone: '07723 051993', membership_number: 'R073', membership_type_id: '9', admin:'false'},
{ first_name: 'Anthony', last_name: 'Worrall', telephone: '07967 817768', membership_number: 'R074', membership_type_id: '9', admin:'false'},
{ first_name: 'Charlotte', last_name: 'Swaddle', telephone: '7905925220', membership_number: 'R076', membership_type_id: '9', admin:'false'},
{ first_name: 'Chris', last_name: 'McLane', telephone: '', membership_number: 'R975', membership_type_id: '9', admin:'false'},
{ first_name: 'Phil', last_name: 'Hall', telephone: '07810 084153', membership_number: 'S003', membership_type_id: '6', admin:'false'},
{ first_name: 'Tony', last_name: 'Guy', telephone: '07894 562528', membership_number: 'S005', membership_type_id: '6', admin:'false'},
{ first_name: 'Angela', last_name: 'Johnson', telephone: '07891 260824', membership_number: 'S008', membership_type_id: '6', admin:'false'},
{ first_name: 'Russell', last_name: 'Hunter', telephone: '07963 940557', membership_number: 'S009', membership_type_id: '6', admin:'false'},
{ first_name: 'Steve', last_name: 'Carney', telephone: '07595 205302', membership_number: 'S025', membership_type_id: '6', admin:'false'},
{ first_name: 'Tim', last_name: 'Mazzucchi', telephone: '07985 563027', membership_number: 'S031', membership_type_id: '6', admin:'false'},
{ first_name: 'Chris', last_name: 'Waller', telephone: '07969 924368', membership_number: 'S054', membership_type_id: '6', admin:'false'},
{ first_name: 'Geoff', last_name: 'Brindle', telephone: '', membership_number: 'S056', membership_type_id: '6', admin:'false'},
{ first_name: 'Patrick', last_name: 'Candon', telephone: '07889 972279', membership_number: 'S082', membership_type_id: '6', admin:'false'},
{ first_name: 'Brian', last_name: 'Hardy', telephone: '07960 242253', membership_number: 'S083', membership_type_id: '6', admin:'false'},
{ first_name: 'Grace', last_name: 'Metcalfe', telephone: '7800944149', membership_number: 'S090', membership_type_id: '6', admin:'false'},
{ first_name: 'Malcolm', last_name: 'Chapman', telephone: '', membership_number: 'S091', membership_type_id: '6', admin:'false'},
{ first_name: 'Allan', last_name: 'Charlton', telephone: '07905 124858', membership_number: 'S093', membership_type_id: '6', admin:'false'},
{ first_name: 'Georgie', last_name: 'Hind', telephone: '7790293677', membership_number: 'S094', membership_type_id: '6', admin:'false'},
{ first_name: 'Maurice', last_name: 'Cliff', telephone: '07738 788908', membership_number: 'S100', membership_type_id: '6', admin:'false'},
{ first_name: 'Alison', last_name: 'Carr', telephone: '07890 864491', membership_number: 'S102', membership_type_id: '6', admin:'false'},
{ first_name: 'Colin', last_name: 'McNestrie', telephone: '07917 358361', membership_number: 'S123', membership_type_id: '6', admin:'false'},
{ first_name: 'Kevin', last_name: 'Jackson', telephone: '07540 697524', membership_number: 'S125', membership_type_id: '6', admin:'false'},
{ first_name: 'David', last_name: 'Fenwick', telephone: '07946 543711', membership_number: 'S126', membership_type_id: '6', admin:'false'},
{ first_name: 'Keith', last_name: 'Shannon', telephone: '07725 057371', membership_number: 'S144', membership_type_id: '6', admin:'false'},
{ first_name: 'Dave', last_name: 'Wood', telephone: '07970 902218', membership_number: 'S149', membership_type_id: '6', admin:'false'},
{ first_name: 'Gary', last_name: 'Eden', telephone: '07949 083534', membership_number: 'S151', membership_type_id: '6', admin:'false'},
{ first_name: 'Keith', last_name: 'Woods', telephone: '07709 708229', membership_number: 'S158', membership_type_id: '6', admin:'false'},
{ first_name: 'Robert', last_name: 'Scott', telephone: '07790 686053', membership_number: 'S159', membership_type_id: '6', admin:'false'},
{ first_name: 'Steve', last_name: 'Calvert', telephone: '7810593981', membership_number: 'S167', membership_type_id: '6', admin:'false'},
{ first_name: 'Edward', last_name: 'Henein', telephone: '07966 230511', membership_number: 'S175', membership_type_id: '6', admin:'false'},
{ first_name: 'Stephen', last_name: 'Cruz', telephone: '07956 356363', membership_number: 'S179', membership_type_id: '6', admin:'false'},
{ first_name: 'John', last_name: 'Gallagher', telephone: '07982 242864', membership_number: 'S192', membership_type_id: '6', admin:'false'},
{ first_name: 'Robin', last_name: 'Gunn', telephone: '', membership_number: 'S197', membership_type_id: '6', admin:'false'},
{ first_name: 'Alan', last_name: 'Love', telephone: '07500 082259', membership_number: 'S199', membership_type_id: '6', admin:'false'},
{ first_name: 'John', last_name: 'Thompson', telephone: '07968 483977', membership_number: 'S213', membership_type_id: '6', admin:'false'},
{ first_name: 'Robert', last_name: 'Brown', telephone: '7837219374', membership_number: 'S245', membership_type_id: '6', admin:'false'},
{ first_name: 'Chris', last_name: 'Potts', telephone: '07825 528289', membership_number: 'S246', membership_type_id: '6', admin:'false'},
{ first_name: 'Scott', last_name: 'McKay', telephone: '07702 508675', membership_number: 'S266', membership_type_id: '6', admin:'false'},
{ first_name: 'Mick', last_name: 'Kennedy', telephone: '07711 756419', membership_number: 'S267', membership_type_id: '6', admin:'false'},
{ first_name: 'Michael', last_name: 'Slater', telephone: '07772 906352', membership_number: 'S268', membership_type_id: '6', admin:'false'},
{ first_name: 'Col', last_name: 'Campbell', telephone: '7500089789', membership_number: 'S269', membership_type_id: '6', admin:'false'},
{ first_name: 'William', last_name: 'Maloney', telephone: '7986663971', membership_number: 'S270', membership_type_id: '6', admin:'false'},
{ first_name: 'Ali', last_name: 'Mitchell', telephone: '7912629011', membership_number: 'S271', membership_type_id: '6', admin:'false'},
{ first_name: 'John', last_name: 'Swanston', telephone: '7796865472', membership_number: 'S272', membership_type_id: '6', admin:'false'},
{ first_name: 'Charles', last_name: 'Goring', telephone: '07785 576196', membership_number: 'S273', membership_type_id: '6', admin:'false'},
{ first_name: 'Paul', last_name: 'Newton', telephone: '7957253996', membership_number: 'S274', membership_type_id: '6', admin:'false'},
{ first_name: 'John', last_name: 'Hearl', telephone: '7763029591', membership_number: 'S275', membership_type_id: '6', admin:'false'},
{ first_name: 'Ron', last_name: 'Grant', telephone: '', membership_number: 'S276', membership_type_id: '6', admin:'false'},
{ first_name: 'Dave', last_name: 'Johnston', telephone: '7921246371', membership_number: 'S277', membership_type_id: '6', admin:'false'},
{ first_name: 'John', last_name: 'Liddle', telephone: '7909103142', membership_number: 'S278', membership_type_id: '6', admin:'false'},
{ first_name: 'Peter', last_name: 'Fargher', telephone: '07824 531408', membership_number: 'S279', membership_type_id: '6', admin:'false'},
{ first_name: 'Keith', last_name: 'Tait', telephone: '07754 467791', membership_number: 'S281', membership_type_id: '6', admin:'false'},
{ first_name: 'David', last_name: 'Favour', telephone: '07808 824663', membership_number: 'S287', membership_type_id: '6', admin:'false'},
{ first_name: 'Mark', last_name: 'Humphreys', telephone: '7715321767', membership_number: 'S288', membership_type_id: '6', admin:'false'},
{ first_name: 'Shaun', last_name: 'Dunn', telephone: '07774 914933', membership_number: 'S294', membership_type_id: '6', admin:'false'},
{ first_name: 'Margaret', last_name: 'Algar', telephone: '7792311348', membership_number: 'S309', membership_type_id: '6', admin:'false'},
{ first_name: 'Ray', last_name: 'Raffle', telephone: '07790 438612', membership_number: 'S316', membership_type_id: '6', admin:'false'},
{ first_name: 'Norman', last_name: 'Orange', telephone: '07850 567365', membership_number: 'S343', membership_type_id: '6', admin:'false'},
{ first_name: 'Lee', last_name: 'Campbell', telephone: '7517353161', membership_number: 'S344', membership_type_id: '6', admin:'false'},
{ first_name: 'Louise', last_name: 'Robertson', telephone: '07985 525149', membership_number: 'S345', membership_type_id: '6', admin:'false'},
{ first_name: 'Mark', last_name: 'Thompson', telephone: '7594350434', membership_number: 'S357', membership_type_id: '6', admin:'false'},
{ first_name: 'Raymond', last_name: 'Thompson', telephone: '7815528872', membership_number: 'S358', membership_type_id: '6', admin:'false'},
{ first_name: 'Daniel', last_name: 'Wilson', telephone: '7584088626', membership_number: 'S359', membership_type_id: '6', admin:'false'},
{ first_name: 'Thomas', last_name: 'Allan', telephone: '7803051803', membership_number: 'S360', membership_type_id: '6', admin:'false'},
{ first_name: 'Michael', last_name: 'Crammond', telephone: '7581184922', membership_number: 'S361', membership_type_id: '6', admin:'false'},
{ first_name: 'Lewis', last_name: 'McManus', telephone: '7817401441', membership_number: 'S362', membership_type_id: '6', admin:'false'},
{ first_name: 'Daniel', last_name: 'McManus', telephone: '7736456407', membership_number: 'S363', membership_type_id: '6', admin:'false'},
{ first_name: 'Mark', last_name: 'McManus', telephone: '7590539870', membership_number: 'S364', membership_type_id: '6', admin:'false'},
{ first_name: 'Darren', last_name: 'Stafford', telephone: '7919925164', membership_number: 'S365', membership_type_id: '6', admin:'false'},
{ first_name: 'Charlotte', last_name: 'Osborn', telephone: '07957 367457', membership_number: 'S379', membership_type_id: '6', admin:'false'},
{ first_name: 'Michael', last_name: 'Sheldon', telephone: '', membership_number: 'S386', membership_type_id: '6', admin:'false'},
{ first_name: 'Tom', last_name: 'Mulligan', telephone: '07711 309977', membership_number: 'S393', membership_type_id: '6', admin:'false'},
{ first_name: 'Chris', last_name: 'Checkley', telephone: '', membership_number: 'S403', membership_type_id: '6', admin:'false'},
{ first_name: 'Nick', last_name: 'Gemmell', telephone: '7817279090', membership_number: 'S404', membership_type_id: '6', admin:'false'},
{ first_name: 'James', last_name: 'Stewart', telephone: '7855392385', membership_number: 'S405', membership_type_id: '6', admin:'false'},
{ first_name: 'Andrew', last_name: 'Gibson', telephone: '7930401167', membership_number: 'S406', membership_type_id: '6', admin:'false'},
{ first_name: 'Oliver', last_name: 'Scholes', telephone: '7518393821', membership_number: 'S407', membership_type_id: '6', admin:'false'},
{ first_name: 'Kevin', last_name: 'Vallely', telephone: '7774980567', membership_number: 'S408', membership_type_id: '6', admin:'false'},
{ first_name: 'Dennis', last_name: 'Knight', telephone: '7763183736', membership_number: 'S409', membership_type_id: '6', admin:'false'},
{ first_name: 'Bob', last_name: 'Graham', telephone: '07779 428108', membership_number: 'S427', membership_type_id: '6', admin:'false'},
{ first_name: 'Barry', last_name: 'Watson', telephone: '07922 044813', membership_number: 'S435', membership_type_id: '6', admin:'false'},
{ first_name: 'Ryan', last_name: 'Dallat', telephone: '7446879969', membership_number: 'S454', membership_type_id: '6', admin:'false'},
{ first_name: 'Adam', last_name: 'Bathgate', telephone: '7949229354', membership_number: 'S456', membership_type_id: '6', admin:'false'},
{ first_name: 'Gill', last_name: 'Mason', telephone: '07939 614423', membership_number: 'S462', membership_type_id: '6', admin:'false'},
{ first_name: 'Nick', last_name: 'Tompkins', telephone: '07771 626857', membership_number: 'S470', membership_type_id: '6', admin:'false'},
{ first_name: 'Norman', last_name: 'Goble', telephone: '07751 935745', membership_number: 'S473', membership_type_id: '6', admin:'false'},
{ first_name: 'Alan', last_name: 'Rowley', telephone: '07852 972729', membership_number: 'S478', membership_type_id: '6', admin:'false'},
{ first_name: 'Dean', last_name: 'Hogarty', telephone: '7796008051', membership_number: 'S479', membership_type_id: '6', admin:'false'},
{ first_name: 'Kevin', last_name: 'Hogarty', telephone: '', membership_number: 'S480', membership_type_id: '6', admin:'false'},
{ first_name: 'Terry', last_name: 'Smart ', telephone: '07894 639904', membership_number: 'S496', membership_type_id: '6', admin:'false'},
{ first_name: 'John', last_name: 'Walsh', telephone: '07847 141133', membership_number: 'S525', membership_type_id: '6', admin:'false'},
{ first_name: 'Chris', last_name: 'Beldon', telephone: '07759 699692', membership_number: 'S531', membership_type_id: '6', admin:'false'},
{ first_name: 'Nick', last_name: 'Cubley', telephone: '07967 276260', membership_number: 'S532', membership_type_id: '6', admin:'false'},
{ first_name: 'David', last_name: 'Wilson', telephone: '07925 679587', membership_number: 'S543', membership_type_id: '6', admin:'false'},
{ first_name: 'Martin', last_name: 'Inskip', telephone: '07974 444813', membership_number: 'S560', membership_type_id: '6', admin:'false'},
{ first_name: 'Doug', last_name: 'Watt', telephone: '07913 008729', membership_number: 'S578', membership_type_id: '6', admin:'false'},
{ first_name: 'Steve', last_name: 'Brown', telephone: '7724010210', membership_number: 'S579', membership_type_id: '6', admin:'false'},
{ first_name: 'Nick', last_name: 'Thornton', telephone: '07834 827545', membership_number: 'S580', membership_type_id: '6', admin:'false'},
{ first_name: 'John', last_name: 'McLean', telephone: '7749709844', membership_number: 'S581', membership_type_id: '6', admin:'false'},
{ first_name: 'Paul', last_name: 'Stonebanks', telephone: '7791080990', membership_number: 'S582', membership_type_id: '6', admin:'false'},
{ first_name: 'Stan', last_name: 'Taylor', telephone: '7710670349', membership_number: 'S583', membership_type_id: '6', admin:'false'},
{ first_name: 'Jim', last_name: 'Allen', telephone: '07976 182129', membership_number: 'S607', membership_type_id: '6', admin:'false'},
{ first_name: 'Dennis', last_name: 'Stewart', telephone: '07802 184315', membership_number: 'S608', membership_type_id: '6', admin:'false'},
{ first_name: 'Kevin', last_name: 'Lowery', telephone: '07775 630961', membership_number: 'S620', membership_type_id: '6', admin:'false'},
{ first_name: 'Norman', last_name: 'Hope', telephone: '07940 653603', membership_number: 'S643', membership_type_id: '6', admin:'false'},
{ first_name: 'Steven', last_name: 'Carlile', telephone: '', membership_number: 'S692', membership_type_id: '6', admin:'false'},
{ first_name: 'Philip', last_name: 'English', telephone: '7970780641', membership_number: 'S693', membership_type_id: '6', admin:'false'},
{ first_name: 'Andy', last_name: 'King', telephone: '07501 133624', membership_number: 'S713', membership_type_id: '6', admin:'false'},
{ first_name: 'Colin', last_name: 'Atchinson', telephone: '07984 616872', membership_number: 'S714', membership_type_id: '6', admin:'false'},
{ first_name: 'Norah', last_name: 'Pedersen', telephone: '07711 845154', membership_number: 'S734', membership_type_id: '6', admin:'false'},
{ first_name: 'Jeff', last_name: 'Legg', telephone: '07905 296997', membership_number: 'S763', membership_type_id: '6', admin:'false'},
{ first_name: 'Marty', last_name: 'Allen', telephone: '07753 949876', membership_number: 'S775', membership_type_id: '6', admin:'false'},
{ first_name: 'Allan', last_name: 'Green', telephone: '07770 917797', membership_number: 'S780', membership_type_id: '6', admin:'false'},
{ first_name: 'David', last_name: 'Armstrong', telephone: '', membership_number: 'S796', membership_type_id: '6', admin:'false'},
{ first_name: 'Carly', last_name: 'Huntley', telephone: '07738 355411', membership_number: 'S805', membership_type_id: '6', admin:'false'},
{ first_name: 'Gordon', last_name: 'Horsley', telephone: '07776 138537', membership_number: 'S811', membership_type_id: '6', admin:'false'},
{ first_name: 'Paul', last_name: 'Easton', telephone: '07957 823896', membership_number: 'S812', membership_type_id: '6', admin:'false'},
{ first_name: 'Dave', last_name: 'Tait', telephone: '07828 008067', membership_number: 'S816', membership_type_id: '6', admin:'false'},
{ first_name: 'Louise', last_name: 'Tupling', telephone: '07942 703739', membership_number: 'S817', membership_type_id: '6', admin:'false'},
{ first_name: 'Paul', last_name: 'Foreman', telephone: '07740 939041', membership_number: 'S818', membership_type_id: '6', admin:'false'},
{ first_name: 'Geoff', last_name: 'Mason', telephone: '', membership_number: 'S845', membership_type_id: '6', admin:'false'},
{ first_name: 'Tony', last_name: 'Crilley', telephone: '07951 853610', membership_number: 'S847', membership_type_id: '6', admin:'false'},
{ first_name: 'Colin', last_name: 'Barrass', telephone: '07903 086045', membership_number: 'S848', membership_type_id: '6', admin:'false'},
{ first_name: 'Michael', last_name: 'McIntyre', telephone: '07811 348126', membership_number: 'S852', membership_type_id: '6', admin:'false'},
{ first_name: 'Craig', last_name: 'Taylor', telephone: '', membership_number: 'S861', membership_type_id: '6', admin:'false'},
{ first_name: 'Ray', last_name: 'Rycroft', telephone: '7584994826', membership_number: 'S865', membership_type_id: '6', admin:'false'},
{ first_name: 'George', last_name: 'Gill', telephone: '', membership_number: 'S869', membership_type_id: '6', admin:'false'},
{ first_name: 'Paul', last_name: 'Albone', telephone: '07538 343168', membership_number: 'S872', membership_type_id: '6', admin:'false'},
{ first_name: 'Stu', last_name: 'Bell', telephone: '07985 110302', membership_number: 'S873', membership_type_id: '6', admin:'false'},
{ first_name: 'Chris', last_name: 'Chapman', telephone: '07795 163059', membership_number: 'S874', membership_type_id: '6', admin:'false'},
{ first_name: 'Jon', last_name: 'Evans', telephone: '7505626448', membership_number: 'S875', membership_type_id: '6', admin:'false'},
{ first_name: 'Mel', last_name: 'Hammond', telephone: '07727 199839', membership_number: 'S879', membership_type_id: '6', admin:'false'},
{ first_name: 'Fred', last_name: 'Iredale', telephone: '07768 634709', membership_number: 'S880', membership_type_id: '6', admin:'false'},
{ first_name: 'Steve', last_name: 'Robertson', telephone: '07939 301715', membership_number: 'S891', membership_type_id: '6', admin:'false'},
{ first_name: 'David', last_name: 'Rowland', telephone: '07802 714060', membership_number: 'S892', membership_type_id: '6', admin:'false'},
{ first_name: 'Philip', last_name: 'Warwick', telephone: '07808 826863', membership_number: 'S897', membership_type_id: '6', admin:'false'},
{ first_name: 'Eric', last_name: 'Mok', telephone: '07979 913238', membership_number: 'S901', membership_type_id: '6', admin:'false'},
{ first_name: 'Richard', last_name: 'Bradley', telephone: '7889059852', membership_number: 'S902', membership_type_id: '6', admin:'false'},
{ first_name: 'Brian', last_name: 'Martindale', telephone: '07917 244594', membership_number: 'S903', membership_type_id: '6', admin:'false'},
{ first_name: 'Simon', last_name: 'Ho', telephone: '07971 258311', membership_number: 'S905', membership_type_id: '6', admin:'false'},
{ first_name: 'Steve', last_name: 'Hodgson', telephone: '07740 879584', membership_number: 'S908', membership_type_id: '6', admin:'false'},
{ first_name: 'Dave', last_name: 'Tomson', telephone: '07939 120076', membership_number: 'S914', membership_type_id: '6', admin:'false'},
{ first_name: 'Lee', last_name: 'Wratten', telephone: '', membership_number: 'S915', membership_type_id: '6', admin:'false'},
{ first_name: 'Tony', last_name: 'Garrity', telephone: '07909 577792', membership_number: 'S918', membership_type_id: '6', admin:'false'},
{ first_name: 'Graeme', last_name: 'Wallace', telephone: '07790 818803', membership_number: 'S921', membership_type_id: '6', admin:'false'},
{ first_name: 'Paul', last_name: 'Stewart', telephone: '', membership_number: 'S922', membership_type_id: '6', admin:'false'},
{ first_name: 'Steve', last_name: 'Lines', telephone: '', membership_number: 'S923', membership_type_id: '6', admin:'false'},
{ first_name: 'Mark', last_name: 'Armstrong ', telephone: '07815 750965', membership_number: 'S924', membership_type_id: '6', admin:'false'},
{ first_name: 'Steve', last_name: 'Wouldhave', telephone: '07824 600111', membership_number: 'S925', membership_type_id: '6', admin:'false'},
{ first_name: 'Alan', last_name: 'Rakison', telephone: '07762 176370', membership_number: 'S926', membership_type_id: '6', admin:'false'},
{ first_name: 'Gordon', last_name: 'Taylor', telephone: '07909 530643', membership_number: 'S930', membership_type_id: '6', admin:'false'},
{ first_name: 'Chris', last_name: 'Reay', telephone: '07976 374629', membership_number: 'S931', membership_type_id: '6', admin:'false'},
{ first_name: 'Alan', last_name: 'Thompson', telephone: '', membership_number: 'S932', membership_type_id: '6', admin:'false'},
{ first_name: 'Mark', last_name: 'Midgley', telephone: '07826 937485', membership_number: 'S936', membership_type_id: '6', admin:'false'},
{ first_name: 'Linda', last_name: 'Bartram', telephone: '07759 350661', membership_number: 'S938', membership_type_id: '6', admin:'false'},
{ first_name: 'Lorna', last_name: 'Berry', telephone: '07899 975566', membership_number: 'S941', membership_type_id: '6', admin:'false'},
{ first_name: 'Jonathan', last_name: 'Brown', telephone: '07816 518478', membership_number: 'S942', membership_type_id: '6', admin:'false'},
{ first_name: 'John', last_name: 'Wilson', telephone: '07808 795955', membership_number: 'S943', membership_type_id: '6', admin:'false'},
{ first_name: 'Marcus', last_name: 'Campbell', telephone: '', membership_number: 'S944', membership_type_id: '6', admin:'false'},
{ first_name: 'Steve', last_name: 'Carrielies', telephone: '', membership_number: 'S945', membership_type_id: '6', admin:'false'},
{ first_name: 'Neil', last_name: 'Mason', telephone: '07779 076442', membership_number: 'S946', membership_type_id: '6', admin:'false'},
{ first_name: 'John', last_name: 'Johnson', telephone: '07721 643631', membership_number: 'S948', membership_type_id: '6', admin:'false'},
{ first_name: 'Brett', last_name: 'Clark', telephone: '07974 767019', membership_number: 'S949', membership_type_id: '6', admin:'false'},
{ first_name: 'John', last_name: 'Simpson', telephone: '07885 794967', membership_number: 'S952', membership_type_id: '6', admin:'false'},
{ first_name: 'Dave', last_name: 'Sedgwick', telephone: '07967 662684', membership_number: 'S953', membership_type_id: '6', admin:'false'},
{ first_name: 'Steven', last_name: 'Elwick', telephone: '07519 075091', membership_number: 'S954', membership_type_id: '6', admin:'false'},
{ first_name: 'Gary', last_name: 'Sharples', telephone: '7904596122', membership_number: 'S956', membership_type_id: '6', admin:'false'},
{ first_name: 'Chris', last_name: 'Wall', telephone: '7738736958', membership_number: 'S957', membership_type_id: '6', admin:'false'},
{ first_name: 'Geoff', last_name: 'Smithson', telephone: '07795 546456', membership_number: 'S958', membership_type_id: '6', admin:'false'},
{ first_name: 'Mark', last_name: 'Newlands', telephone: '07504 715133', membership_number: 'S959', membership_type_id: '6', admin:'false'},
{ first_name: 'Nik', last_name: 'Lowery', telephone: '07974 132068', membership_number: 'S961', membership_type_id: '6', admin:'false'},
{ first_name: 'Kane', last_name: 'Mather', telephone: '', membership_number: 'S965', membership_type_id: '6', admin:'false'},
{ first_name: 'Neil', last_name: 'Pringle', telephone: '07717 786855', membership_number: 'S966', membership_type_id: '6', admin:'false'},
{ first_name: 'Ken', last_name: 'Willis', telephone: '07939 001225', membership_number: 'S967', membership_type_id: '6', admin:'false'},
{ first_name: 'Paul', last_name: 'Allen', telephone: '', membership_number: 'S968', membership_type_id: '6', admin:'false'},
{ first_name: 'Alan', last_name: 'Rycroft', telephone: '07971 001384', membership_number: 'S969', membership_type_id: '6', admin:'false'},
{ first_name: 'Alan', last_name: 'Richardson', telephone: '07770 404745', membership_number: 'S970', membership_type_id: '6', admin:'false'},
{ first_name: 'Ian', last_name: 'Marks', telephone: '07917 441368', membership_number: 'S971', membership_type_id: '6', admin:'false'},
{ first_name: 'Mike', last_name: 'De Vies', telephone: '07969 875379', membership_number: 'S972', membership_type_id: '6', admin:'false'},
{ first_name: 'Adam', last_name: 'Oliver', telephone: '7824394205', membership_number: 'S974', membership_type_id: '6', admin:'false'},
{ first_name: 'Anna', last_name: 'Magri', telephone: '07817 406882', membership_number: 'S978', membership_type_id: '6', admin:'false'},
{ first_name: 'Richard', last_name: 'William', telephone: '07590 927172', membership_number: 'S979', membership_type_id: '6', admin:'false'},
{ first_name: 'Derek', last_name: 'Cogle', telephone: '07809 617433', membership_number: 'S980', membership_type_id: '6', admin:'false'},
{ first_name: 'Steve', last_name: 'Smith ', telephone: '07973 550193', membership_number: 'S984', membership_type_id: '6', admin:'false'},
{ first_name: 'Fiona', last_name: 'MacFarlane', telephone: '07866 516351', membership_number: 'S987', membership_type_id: '6', admin:'false'},
{ first_name: 'Helen', last_name: 'Watson', telephone: '07739 967219', membership_number: 'S989', membership_type_id: '6', admin:'false'},
{ first_name: 'David', last_name: 'Gebhard', telephone: '07768 637680', membership_number: 'S990', membership_type_id: '6', admin:'false'},
{ first_name: 'David', last_name: 'Moir', telephone: '07780 114789', membership_number: 'S993', membership_type_id: '6', admin:'false'},
{ first_name: 'Dave', last_name: 'Forrest', telephone: '', membership_number: 'S996', membership_type_id: '6', admin:'false'},
{ first_name: 'Kate', last_name: 'Haley', telephone: '7935966186', membership_number: 'T099', membership_type_id: '10', admin:'false'},
{ first_name: 'Zac', last_name: 'White', telephone: '7951039988', membership_number: 'T100', membership_type_id: '10', admin:'false'},
{ first_name: 'Nick', last_name: 'Hunter', telephone: '7854252816', membership_number: 'T101', membership_type_id: '10', admin:'false'},
{ first_name: 'Roland', last_name: 'Glancy', telephone: '7786930590', membership_number: 'T102', membership_type_id: '10', admin:'false'},
{ first_name: 'Cait', last_name: 'Foley', telephone: '7786393260', membership_number: 'T105', membership_type_id: '10', admin:'false'},
{ first_name: 'Dave', last_name: 'Hamilton', telephone: '7730415714', membership_number: 'T106', membership_type_id: '10', admin:'false'},
{ first_name: 'Rouven', last_name: 'Snowdon', telephone: '7980564534', membership_number: 'T108', membership_type_id: '10', admin:'false'},
{ first_name: 'Campbell', last_name: 'Maclachlan', telephone: '7799695833', membership_number: 'T109', membership_type_id: '10', admin:'false'},
{ first_name: 'Jamie', last_name: 'Scott', telephone: '7782304182', membership_number: 'T110', membership_type_id: '10', admin:'false'},
{ first_name: 'Kathryn', last_name: 'Moore', telephone: '7500667663', membership_number: 'T112', membership_type_id: '10', admin:'false'},
{ first_name: 'Marc', last_name: 'Mawson', telephone: '7808646818', membership_number: 'T114', membership_type_id: '10', admin:'false'},
{ first_name: 'James', last_name: 'McMichael', telephone: '7834986287', membership_number: 'T115', membership_type_id: '10', admin:'false'},
{ first_name: 'Chris', last_name: 'Wilde', telephone: '7846560432', membership_number: 'T116', membership_type_id: '10', admin:'false'},
{ first_name: 'David', last_name: 'Toole', telephone: '', membership_number: 'T118', membership_type_id: '10', admin:'false'},
{ first_name: 'Nick', last_name: 'Hale', telephone: '7738858501', membership_number: 'T119', membership_type_id: '10', admin:'false'},
])

Court.create([
{ court_name: 'Court 1'},
{ court_name: 'Court 2'},
{ court_name: 'Court 3'},
{ court_name: 'Court 4'},
{ court_name: 'Court 5'},
])

#weekdays
TimeSlot.create([
{ time: Time.zone.parse('09:10'), weekday: false, court_id: 1},
{ time: Time.zone.parse('09:50'), weekday: false, court_id: 1},
{ time: Time.zone.parse('10:30'), weekday: false, court_id: 1},
{ time: Time.zone.parse('11:10'), weekday: false, court_id: 1},
{ time: Time.zone.parse('11:50'), weekday: false, court_id: 1},
{ time: Time.zone.parse('12:30'), weekday: true, court_id: 1},
{ time: Time.zone.parse('13:10'), weekday: true, court_id: 1},
{ time: Time.zone.parse('13:50'), weekday: true, court_id: 1},
{ time: Time.zone.parse('14:30'), weekday: true, court_id: 1},
{ time: Time.zone.parse('15:10'), weekday: true, court_id: 1},
{ time: Time.zone.parse('15:50'), weekday: true, court_id: 1},
{ time: Time.zone.parse('16:30'), weekday: true, court_id: 1},
{ time: Time.zone.parse('17:10'), weekday: true, court_id: 1},
{ time: Time.zone.parse('17:50'), weekday: true, court_id: 1},
{ time: Time.zone.parse('18:30'), weekday: true, court_id: 1},
{ time: Time.zone.parse('19:10'), weekday: true, court_id: 1},
{ time: Time.zone.parse('19:50'), weekday: true, court_id: 1},
{ time: Time.zone.parse('20:30'), weekday: true, court_id: 1},
{ time: Time.zone.parse('21:10'), weekday: true, court_id: 1},
{ time: Time.zone.parse('21:50'), weekday: true, court_id: 1},

{ time: Time.zone.parse('09:10'), weekday: false, court_id: 2},
{ time: Time.zone.parse('09:50'), weekday: false, court_id: 2},
{ time: Time.zone.parse('10:30'), weekday: false, court_id: 2},
{ time: Time.zone.parse('11:10'), weekday: false, court_id: 2},
{ time: Time.zone.parse('11:50'), weekday: false, court_id: 2},
{ time: Time.zone.parse('12:30'), weekday: true, court_id: 2},
{ time: Time.zone.parse('13:10'), weekday: true, court_id: 2},
{ time: Time.zone.parse('13:50'), weekday: true, court_id: 2},
{ time: Time.zone.parse('14:30'), weekday: true, court_id: 2},
{ time: Time.zone.parse('15:10'), weekday: true, court_id: 2},
{ time: Time.zone.parse('15:50'), weekday: true, court_id: 2},
{ time: Time.zone.parse('16:30'), weekday: true, court_id: 2},
{ time: Time.zone.parse('17:10'), weekday: true, court_id: 2},
{ time: Time.zone.parse('17:50'), weekday: true, court_id: 2},
{ time: Time.zone.parse('18:30'), weekday: true, court_id: 2},
{ time: Time.zone.parse('19:10'), weekday: true, court_id: 2},
{ time: Time.zone.parse('19:50'), weekday: true, court_id: 2},
{ time: Time.zone.parse('20:30'), weekday: true, court_id: 2},
{ time: Time.zone.parse('21:10'), weekday: true, court_id: 2},
{ time: Time.zone.parse('21:50'), weekday: true, court_id: 2},

{ time: Time.zone.parse('09:00'), weekday: false, court_id: 3},
{ time: Time.zone.parse('09:40'), weekday: false, court_id: 3},
{ time: Time.zone.parse('10:20'), weekday: false, court_id: 3},
{ time: Time.zone.parse('11:00'), weekday: false, court_id: 3},
{ time: Time.zone.parse('11:40'), weekday: false, court_id: 3},
{ time: Time.zone.parse('12:20'), weekday: true, court_id: 3},
{ time: Time.zone.parse('13:00'), weekday: true, court_id: 3},
{ time: Time.zone.parse('13:40'), weekday: true, court_id: 3},
{ time: Time.zone.parse('14:20'), weekday: true, court_id: 3},
{ time: Time.zone.parse('15:00'), weekday: true, court_id: 3},
{ time: Time.zone.parse('15:40'), weekday: true, court_id: 3},
{ time: Time.zone.parse('16:20'), weekday: true, court_id: 3},
{ time: Time.zone.parse('17:00'), weekday: true, court_id: 3},
{ time: Time.zone.parse('17:40'), weekday: true, court_id: 3},
{ time: Time.zone.parse('18:20'), weekday: true, court_id: 3},
{ time: Time.zone.parse('19:00'), weekday: true, court_id: 3},
{ time: Time.zone.parse('19:40'), weekday: true, court_id: 3},
{ time: Time.zone.parse('20:20'), weekday: true, court_id: 3},
{ time: Time.zone.parse('21:00'), weekday: true, court_id: 3},
{ time: Time.zone.parse('21:40'), weekday: true, court_id: 3},

{ time: Time.zone.parse('09:00'), weekday: false, court_id: 4},
{ time: Time.zone.parse('09:40'), weekday: false, court_id: 4},
{ time: Time.zone.parse('10:20'), weekday: false, court_id: 4},
{ time: Time.zone.parse('11:00'), weekday: false, court_id: 4},
{ time: Time.zone.parse('11:40'), weekday: false, court_id: 4},
{ time: Time.zone.parse('12:20'), weekday: true, court_id: 4},
{ time: Time.zone.parse('13:00'), weekday: true, court_id: 4},
{ time: Time.zone.parse('13:40'), weekday: true, court_id: 4},
{ time: Time.zone.parse('14:20'), weekday: true, court_id: 4},
{ time: Time.zone.parse('15:00'), weekday: true, court_id: 4},
{ time: Time.zone.parse('15:40'), weekday: true, court_id: 4},
{ time: Time.zone.parse('16:20'), weekday: true, court_id: 4},
{ time: Time.zone.parse('17:00'), weekday: true, court_id: 4},
{ time: Time.zone.parse('17:40'), weekday: true, court_id: 4},
{ time: Time.zone.parse('18:20'), weekday: true, court_id: 4},
{ time: Time.zone.parse('19:00'), weekday: true, court_id: 4},
{ time: Time.zone.parse('19:40'), weekday: true, court_id: 4},
{ time: Time.zone.parse('20:20'), weekday: true, court_id: 4},
{ time: Time.zone.parse('21:00'), weekday: true, court_id: 4},
{ time: Time.zone.parse('21:40'), weekday: true, court_id: 4},

{ time: Time.zone.parse('09:05'), weekday: false, court_id: 5},
{ time: Time.zone.parse('09:45'), weekday: false, court_id: 5},
{ time: Time.zone.parse('10:25'), weekday: false, court_id: 5},
{ time: Time.zone.parse('11:05'), weekday: false, court_id: 5},
{ time: Time.zone.parse('11:45'), weekday: false, court_id: 5},
{ time: Time.zone.parse('12:25'), weekday: true, court_id: 5},
{ time: Time.zone.parse('13:05'), weekday: true, court_id: 5},
{ time: Time.zone.parse('13:45'), weekday: true, court_id: 5},
{ time: Time.zone.parse('14:25'), weekday: true, court_id: 5},
{ time: Time.zone.parse('15:05'), weekday: true, court_id: 5},
{ time: Time.zone.parse('15:45'), weekday: true, court_id: 5},
{ time: Time.zone.parse('16:25'), weekday: true, court_id: 5},
{ time: Time.zone.parse('17:05'), weekday: true, court_id: 5},
{ time: Time.zone.parse('17:45'), weekday: true, court_id: 5},
{ time: Time.zone.parse('18:25'), weekday: true, court_id: 5},
{ time: Time.zone.parse('19:05'), weekday: true, court_id: 5},
{ time: Time.zone.parse('19:45'), weekday: true, court_id: 5},
{ time: Time.zone.parse('20:25'), weekday: true, court_id: 5},
{ time: Time.zone.parse('21:05'), weekday: true, court_id: 5},
{ time: Time.zone.parse('21:45'), weekday: true, court_id: 5},
])

#weekdays